"use client";
import {useEffect,useMemo,useRef,useState,type CSSProperties} from "react";
import type {PlannedActivity,UnitPeriod,UnitProgress} from "./local-store";
import WeekStrip from "./WeekStrip";

const ar=(value:number)=>value.toLocaleString("ar-SA",{useGrouping:true});

function RingGauge({totalRatio,activeRatio,totalDone,activeDone,activeLabel}:{totalRatio:number;activeRatio:number;totalDone:number;activeDone:number;activeLabel:string}){
 const dash=(ratio:number)=>`${Math.max(0,Math.min(1,ratio))*100} 100`;
 return <div className="gauge-ring-face"><svg viewBox="0 0 240 240" aria-hidden="true"><g transform="rotate(-90 120 120)"><circle className="gauge-ring-track gauge-ring-outer" cx="120" cy="120" r="94" pathLength="100"/><circle className="gauge-ring-day" cx="120" cy="120" r="94" pathLength="100" style={{strokeDasharray:dash(totalRatio)}}/><circle className="gauge-ring-track gauge-ring-inner" cx="120" cy="120" r="68" pathLength="100"/><circle className="gauge-ring-period" cx="120" cy="120" r="68" pathLength="100" style={{strokeDasharray:dash(activeRatio)}}/></g><text className="gauge-ring-label" x="120" y="99">تم إنجاز</text><text className="gauge-ring-value" x="120" y="129">{ar(totalDone)}</text><text className="gauge-ring-period-label" x="120" y="153">{activeLabel.replace(/^بعد\s+/,"")} · {ar(activeDone)}</text></svg></div>
}

export default function DhikrRunner({activity,date,today,currentPeriodIndex,calendarMode,initialPeriod,initial,onExit,onEdit,onChange,onFinish,onDateChange}:{activity:PlannedActivity;date:string;today:string;currentPeriodIndex:number;calendarMode:"islamic"|"gregory"|"mixed";initialPeriod?:string;initial?:UnitProgress;onExit:()=>void;onEdit:()=>void;onChange:(progress:UnitProgress)=>void;onFinish:(total:number)=>void;onDateChange:(offset:number)=>void}){
 const config=activity.unitTracking!;
 const configuredPeriods=config.periods.length?config.periods:[{id:"daily",label:activity.period,period:activity.period,target:config.target,unitCount:Math.max(1,Math.ceil(config.target/Math.max(1,config.pressValue))),unitValue:config.pressValue}];
 const basePeriods=configuredPeriods.filter((period,index,all)=>all.findIndex(item=>item.period===period.period)===index);
 const [selected,setSelected]=useState(()=>basePeriods.find(period=>period.period===initialPeriod)?.id??basePeriods[0].id);
 const [progress,setProgress]=useState<UnitProgress>(initial??{activityId:activity.id,date,counterByPeriod:{},completedUnitsByPeriod:{},updatedAt:new Date().toISOString()});
 const [operationHistory,setOperationHistory]=useState<Record<string,{counter:number;units:number[]}[]>>({}),[feedback,setFeedback]=useState<{amount:number;kind:"add"|"undo";id:number}|null>(null);
 const [decrementMode,setDecrementMode]=useState(false),holdTimer=useRef<number|null>(null),longPressTriggered=useRef(false);
 const [celebration,setCelebration]=useState<{message:string;id:number}|null>(null);
 const periods=useMemo(()=>basePeriods.map(period=>{const target=progress.targetByPeriod?.[period.id]??period.target;return{...period,target,unitCount:Math.max(1,Math.ceil(target/period.unitValue))}}),[basePeriods,progress.targetByPeriod]);
 const active=periods.find(period=>period.id===selected)??periods[0];
 const doneFor=(period:UnitPeriod,source=progress)=>Math.max(source.counterByPeriod[period.id]??0,(source.completedUnitsByPeriod[period.id]?.length??0)*period.unitValue);
 const gaugeStyle=config.gaugeStyle??"ring";
 const totalTarget=periods.reduce((sum,period)=>sum+period.target,0),totalDone=periods.reduce((sum,period)=>sum+doneFor(period),0);
 const dailyRemaining=Math.max(0,totalTarget-totalDone);
 const totalPercent=totalTarget?Math.min(100,Math.round(totalDone/totalTarget*100)):0;
 const totalRatio=totalTarget?Math.min(1,totalDone/totalTarget):0;
 // تدريجات بصرية محدودة؛ العداد العام للمنجز، وهدف الفترة يظهر كنص مستقل.
 const gaugeTicks=Array.from({length:9},(_,index)=>(index+1)/10);
 const dayEnded=date<today;
 const persist=(next:UnitProgress)=>{const nextPeriods=basePeriods.map(period=>({...period,target:next.targetByPeriod?.[period.id]??period.target}));const completed=nextPeriods.every(period=>doneFor(period,next)>=period.target);const saved={...next,updatedAt:new Date().toISOString(),completedAt:completed?(next.completedAt??new Date().toISOString()):undefined};setProgress(saved);onChange(saved);if(completed&&!progress.completedAt)onFinish(nextPeriods.reduce((sum,period)=>sum+period.target,0))};
 const add=(amount:number)=>{const before=doneFor(active);if(decrementMode&&before===0)return;const units=[...(progress.completedUnitsByPeriod[active.id]??[])],nextCount=decrementMode?Math.max(0,before-amount):before+amount,kind=decrementMode?"undo":"add";setOperationHistory(current=>({...current,[active.id]:[...(current[active.id]??[]),{counter:progress.counterByPeriod[active.id]??0,units}]}));setFeedback({amount,kind,id:Date.now()});const next={...progress,counterByPeriod:{...progress.counterByPeriod,[active.id]:nextCount},completedUnitsByPeriod:decrementMode?{...progress.completedUnitsByPeriod,[active.id]:[]}:progress.completedUnitsByPeriod};if(!decrementMode&&before<active.target&&nextCount>=active.target){const messages=["أحسنت صنعًا","رائع، لقد أنجزت","بارك الله فيك","كم أنت بطل"];setCelebration({message:messages[Math.floor(Math.random()*messages.length)],id:Date.now()})}persist(next)};
 const undo=()=>{const history=operationHistory[active.id]??[],last=history.at(-1);if(!last)return;const before=doneFor(active),restored=Math.max(last.counter,last.units.length*active.unitValue);setOperationHistory(current=>({...current,[active.id]:history.slice(0,-1)}));setFeedback({amount:Math.abs(restored-before),kind:restored>=before?"add":"undo",id:Date.now()});persist({...progress,completedAt:undefined,counterByPeriod:{...progress.counterByPeriod,[active.id]:last.counter},completedUnitsByPeriod:{...progress.completedUnitsByPeriod,[active.id]:last.units}})};
 const startModeHold=()=>{if(holdTimer.current!==null)window.clearTimeout(holdTimer.current);longPressTriggered.current=false;holdTimer.current=window.setTimeout(()=>{longPressTriggered.current=true;setDecrementMode(value=>!value)},520)};
 const endModeHold=()=>{if(holdTimer.current!==null){window.clearTimeout(holdTimer.current);holdTimer.current=null}};
 useEffect(()=>{if(!feedback)return;const timer=window.setTimeout(()=>setFeedback(null),760);return()=>window.clearTimeout(timer)},[feedback]);
 useEffect(()=>{if(!celebration)return;const timer=window.setTimeout(()=>setCelebration(null),3000);return()=>window.clearTimeout(timer)},[celebration]);
 const adjustPeriodUnits=(period:UnitPeriod,change:number)=>{const target=Math.max(period.unitValue,period.target+(change*period.unitValue));persist({...progress,completedAt:undefined,targetByPeriod:{...(progress.targetByPeriod??{}),[period.id]:target}})};
 const periodOrder=["الصباح","الظهر","العصر","المغرب","الليل"];
 const isMissed=(period:UnitPeriod)=>date<today||(date===today&&periodOrder.indexOf(period.period)<currentPeriodIndex);
 return <section className="dhikr-runner">
  <header><button className="dhikr-exit" onClick={onExit} aria-label="العودة إلى رحلة اليوم" title="العودة إلى رحلة اليوم">↩</button><div><small>ورد اليوم</small><h1>{activity.name}</h1></div><div className="dhikr-head-actions"><button onClick={onEdit} aria-label="تعديل الورد" title="تعديل الورد"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m14.7 4.1 5.2 5.2M5 19l3.8-.8L19.2 7.8a2 2 0 0 0 0-2.8l-.2-.2a2 2 0 0 0-2.8 0L5.8 15.2 5 19Z"/></svg></button></div></header>
  <WeekStrip date={date} today={today} calendarMode={calendarMode} onChange={next=>{const current=new Date(`${date}T12:00:00`),target=new Date(`${next}T12:00:00`);onDateChange(Math.round((target.getTime()-current.getTime())/86400000))}}/>
  <article className="dhikr-overview-card">
   <div className="dhikr-day-total dhikr-gauge-summary" aria-label="ملخص ورد اليوم">
    <div className={`dhikr-gauge gauge-${gaugeStyle}`}>
     <RingGauge totalRatio={totalRatio} activeRatio={active.target?Math.min(1,doneFor(active)/active.target):0} totalDone={totalDone} activeDone={doneFor(active)} activeLabel={active.label}/>
     <svg className="gauge-semi" viewBox="0 0 240 160" aria-hidden="true"><defs><clipPath id="gauge-shared-cut"><rect x="0" y="0" width="240" height="132"/></clipPath><filter id="gauge-needle-soft-shadow" filterUnits="userSpaceOnUse" x="-20" y="-10" width="280" height="180"><feGaussianBlur in="SourceGraphic" stdDeviation="3.1" result="needleBlur"/><feOffset in="needleBlur" dx="1" dy="3.8"/></filter><filter id="gauge-dial-soft-shadow" filterUnits="userSpaceOnUse" x="-20" y="-20" width="280" height="220"><feGaussianBlur stdDeviation="3.8"/></filter></defs><g clipPath="url(#gauge-shared-cut)"><path className="gauge-track" pathLength="100" d="M220 132V118 A100 100 0 0 0 20 118V132"/><path className="gauge-leg-fill" style={{opacity:totalDone>0?1:0}} d="M220 132V118"/><path className="gauge-fill" pathLength="100" style={{strokeDasharray:`${totalPercent} 100`}} d="M220 118 A100 100 0 0 0 20 118"/>{totalPercent===100&&<path className="gauge-leg-fill" d="M20 118V132"/>}{gaugeTicks.map((ratio,index)=>{const angle=-Math.PI*ratio,x1=120+98*Math.cos(angle),y1=118+98*Math.sin(angle),x2=120+103*Math.cos(angle),y2=118+103*Math.sin(angle);return <line key={index} className="gauge-tick" x1={x1} y1={y1} x2={x2} y2={y2}/>})}<g className={feedback?["gauge-needle",feedback.kind].join(" "):"gauge-needle"} style={{transform:`rotate(${-totalRatio*180}deg)`}}><line filter="url(#gauge-needle-soft-shadow)" className="gauge-needle-shadow" x1="120" y1="118" x2="226" y2="118"/><line className="gauge-needle-face" x1="120" y1="118" x2="226" y2="118"/></g><g className="gauge-dial"><circle filter="url(#gauge-dial-soft-shadow)" className="gauge-dial-shadow" cx="120" cy="118" r="60"/><circle className="gauge-dial-halo" cx="120" cy="118" r="63"/><circle className="gauge-dial-face" cx="120" cy="118" r="56"/><text className="gauge-dial-label" x="120" y="84">تم إنجاز</text><text className={feedback?["gauge-dial-value","number-feedback",feedback.kind].join(" "):"gauge-dial-value"} x="120" y="116">{ar(totalDone)}</text></g></g></svg>
    </div>
    <p className="gauge-period-goal">هدف اليوم <b>{ar(totalTarget)}</b> ذكرًا</p><p className={`dhikr-goal-remaining ${dayEnded&&dailyRemaining>0?"late":""}`}>{dailyRemaining>0?<>تبقّى لإنجاز هدفك <b>{ar(dailyRemaining)}</b> ذكرًا</>:"أتممت هدفك اليوم"}</p>
   </div>
   <div className="dhikr-station-tracks">{periods.map(period=>{const done=doneFor(period),periodProgress=Math.min(100,period.target?Math.round(done/period.target*100):0),complete=done>=period.target,feedbackKind=selected===period.id?feedback?.kind:null;return <article key={period.id} className={`dhikr-station-row ${selected===period.id?"selected":""} ${complete?"complete":""} ${!complete&&isMissed(period)?"missed":""}`} onClick={()=>setSelected(period.id)}><button className="dhikr-station-main" onClick={()=>setSelected(period.id)} aria-label={`${period.label}: ${ar(done)} من ${ar(period.target)}، اختر للعمل عليها`}><span>{period.label.replace(/^بعد\s+/,"")}</span><i><b style={{"--period-progress":String(periodProgress/100)} as CSSProperties}/><em className={feedbackKind?["pulse",feedbackKind].join(" "):""} style={{right:`${periodProgress}%`}}>{ar(done)}</em></i></button><div className="dhikr-row-units" aria-label={`العدد المطلوب في ${period.label}`}><button className="dhikr-unit-step" onClick={event=>{event.stopPropagation();adjustPeriodUnits(period,-1)}} disabled={period.target<=period.unitValue} aria-label="إنقاص العدد المطلوب">−</button><b>{ar(period.target)}</b><button className="dhikr-unit-step" onClick={event=>{event.stopPropagation();adjustPeriodUnits(period,1)}} aria-label="زيادة العدد المطلوب">+</button></div></article>})}</div>
  </article>
  <div className="dhikr-counter"><div className="dhikr-counter-choices">{[1,10,100].map(amount=><button key={amount} className={decrementMode?"decrement-mode":""} disabled={decrementMode&&doneFor(active)===0} onClick={()=>add(amount)}><small>كل ضغطة</small><b>{decrementMode?"−":"+"}{ar(amount)}</b>{feedback?.amount===amount&&<em key={feedback.id} className={`counter-feedback ${feedback.kind}`}>{feedback.kind==="add"?"+":"−"}{ar(amount)}</em>}</button>)}<button className={`dhikr-undo ${decrementMode?"decrement-mode":""} ${operationHistory[active.id]?.length?"":"undo-unavailable"}`} onPointerDown={startModeHold} onPointerUp={endModeHold} onPointerLeave={()=>{endModeHold();longPressTriggered.current=false}} onPointerCancel={()=>{endModeHold();longPressTriggered.current=false}} onKeyDown={event=>{if((event.key==="Enter"||event.key===" ")&&!event.repeat)startModeHold()}} onKeyUp={endModeHold} onBlur={endModeHold} onContextMenu={event=>event.preventDefault()} onClick={()=>{if(longPressTriggered.current){longPressTriggered.current=false;return}if(decrementMode){setDecrementMode(false);return}undo()}} aria-pressed={decrementMode} aria-label={decrementMode?"إيقاف وضع الإنقاص":"تراجع عن آخر عملية؛ اضغط مطولًا لتفعيل الإنقاص"} title={decrementMode?"اضغط للعودة إلى الزيادة":"اضغط للتراجع أو اضغط مطولًا لتفعيل الإنقاص"}><span className="undo-icon" aria-hidden="true">{decrementMode?<svg viewBox="0 0 24 24" fill="none"><path d="M5 12h14M12 5v14"/></svg>:<svg viewBox="0 0 24 24" fill="none"><path d="M8.2 8.4H4.5v-3.7M4.9 8.1a8 8 0 1 1-1 8.3"/><path d="M4.9 8.1 8.2 4.8"/></svg>}</span><small>{decrementMode?"إنقاص":"تراجع"}</small></button></div></div>
  {totalDone>=totalTarget&&<div className="dhikr-complete"><b>تم ورد اليوم.</b><span>انتهيت. أكمل يومك بهدوء.</span></div>}
  {celebration&&<div key={celebration.id} className="dhikr-celebration" role="status" aria-live="polite"><div className="dhikr-celebration-card"><svg className="dhikr-celebration-art" viewBox="0 0 96 96" aria-hidden="true"><path className="celebration-rays" d="M48 5v10M48 81v10M5 48h10M81 48h10M17.6 17.6l7 7M71.4 71.4l7 7M78.4 17.6l-7 7M24.6 71.4l-7 7"/><circle className="celebration-medal" cx="48" cy="43" r="25"/><path className="celebration-ribbon" d="m33 63-4 20 19-9 19 9-4-20"/><path className="celebration-check" d="m37 43 8 8 15-17"/></svg><strong>{celebration.message}</strong><span>أتممت هدف هذه الفترة</span></div></div>}
 </section>
}
