"use client";
import { useEffect, useMemo, useState } from "react";
import { activities, settings, templates, type Tab } from "./data";
import { clockLabel, durationLabel, fitsWindow, getRiyadhPrayerTimes, minuteClockLabel, resolveTimeWindow } from "./time-engine";
import { deleteAppointment, deletePlan, deleteTask, readAppointments, readExecutionLog, readPlan, readTasks, readUnitProgress, saveAppointment, saveExecution, savePlan, saveTask, saveUnitProgress, updateAppointment, updatePlan, updateTask, type Appointment, type ExecutionRecord, type PlannedActivity, type TaskItem, type UnitPeriod, type UnitProgress, type WorkoutExercise } from "./local-store";
import WorkoutRunner from "./WorkoutRunner";
import DhikrRunner from "./DhikrRunner";
import { calisthenicsCatalog } from "./workout-data";
import {ProfileDrawer,SectionScreen,TaskDialog,type SectionKind} from "./SectionScreens";

type Phase="idle"|"running"|"paused"|"done";
type JourneyFilter="all"|"goals"|"commitments"|"tasks"|"appointments";
const slots=[
 {time:"—",period:"الصباح",activity:"القراءة",amount:"٥ صفحات",minutes:15,note:"أنجز… ولو لم تستمتع يا هذا.",reading:true,next:"الظهر"},
 {time:"١٣:٠٠",period:"الظهر",activity:"المشي",amount:"٢٠ دقيقة",minutes:20,note:"قم وامشِ. التفكير في المشي لا يُحسب مشيًا.",next:"العصر بعد ٣:٣٠"},
 {time:"١٦:٣٠",period:"العصر",activity:"الرياضة",amount:"٣٠ دقيقة فقط",minutes:30,note:"أنجزها الآن، واستمتع بباقي وقتك.",next:"المغرب بعد ٢:٢٥"},
 {time:"—",period:"المغرب",activity:"المهارة",amount:"٢٠ دقيقة",minutes:20,note:"جلسة واحدة تكفي. لا نؤلف ملحمة.",next:"الليل"},
 {time:"—",period:"الليل",activity:"النوم",amount:"٧ ساعات",minutes:420,note:"يكفي لهذا اليوم. أغلقه بهدوء.",next:"الصباح"},
];
const nav:{id:Tab;label:string;icon:string}[]=[{id:"goals",label:"الأهداف",icon:"↗"},{id:"commitments",label:"الالتزامات",icon:"◌"},{id:"now",label:"الآن",icon:"●"},{id:"tasks",label:"المهام",icon:"✓"},{id:"appointments",label:"المواعيد",icon:"◷"}];
const arNumber=(value:number,pad=1)=>value.toLocaleString("ar-SA",{minimumIntegerDigits:Math.max(1,pad),useGrouping:false});
const fmt=(s:number)=>`${arNumber(Math.floor(s/60),2)}:${arNumber(s%60,2)}`;
const timeToMinutes=(value:string)=>{const [hours,minutes]=value.split(":").map(Number);return hours*60+minutes};
const arabicTime=(value:string)=>{const [hours,minutes]=value.split(":").map(Number);const suffix=hours>=12?"م":"ص";return `${arNumber(((hours+11)%12)+1)}:${arNumber(minutes,2)} ${suffix}`};
const appointmentPeriod=(time:string,starts:number[])=>{const minute=timeToMinutes(time);for(let i=starts.length-1;i>=0;i--)if(minute>=starts[i])return i;return 4};
const unitPeriodFor=(activity:PlannedActivity,period:string)=>activity.unitTracking?.periods.find(item=>item.period===period)??activity.unitTracking?.periods[0];
const unitDone=(progress:UnitProgress|undefined,period:UnitPeriod|undefined)=>!progress||!period?0:Math.min(period.target,Math.max(progress.counterByPeriod[period.id]??0,(progress.completedUnitsByPeriod[period.id]?.length??0)*period.unitValue));
const weekDayName=(date:Date)=>new Intl.DateTimeFormat("ar-SA",{weekday:"long",timeZone:"Asia/Riyadh"}).format(date);
const scheduledOn=(activity:PlannedActivity,date:Date)=>activity.schedule.mode==="daily"||Boolean(activity.schedule.days?.includes(weekDayName(date))||activity.schedule.value.includes(weekDayName(date)));

export default function Home(){
 const [tab,setTab]=useState<Tab>("now"),[drawerOpen,setDrawerOpen]=useState(false),[journeyFilter,setJourneyFilter]=useState<JourneyFilter>("all"),[journeyDate,setJourneyDate]=useState<Date|null>(null),[viewMotion,setViewMotion]=useState<"forward"|"back"|null>(null),[creationNature,setCreationNature]=useState<"goal"|"commitment">("commitment"),[calendarMode,setCalendarMode]=useState<"islamic"|"gregory">("gregory"),[activeWorkout,setActiveWorkout]=useState<PlannedActivity|null>(null),[activeDhikr,setActiveDhikr]=useState<PlannedActivity|null>(null),[unitProgress,setUnitProgress]=useState<UnitProgress[]>([]),[runningActivity,setRunningActivity]=useState<PlannedActivity|null>(null),[editingActivity,setEditingActivity]=useState<PlannedActivity|null>(null),[editingTask,setEditingTask]=useState<TaskItem|null>(null),[editingAppointment,setEditingAppointment]=useState<Appointment|null>(null),[previewIndex,setPreviewIndex]=useState(2),[dayPeriod,setDayPeriod]=useState<number|null>(null),[live,setLive]=useState(true),[clock,setClock]=useState<Date|null>(null),[phase,setPhase]=useState<Phase>("idle"),[pages,setPages]=useState(0),[prayer,setPrayer]=useState(""),[range,setRange]=useState("week"),[plan,setPlan]=useState<PlannedActivity[]>([]),[tasks,setTasks]=useState<TaskItem[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[executionRecords,setExecutionRecords]=useState<ExecutionRecord[]>([]),[savedCount,setSavedCount]=useState(0); const fallbackClock=new Date(2020,0,1,16,30); const windowNow=resolveTimeWindow(clock??fallbackClock); const prayerStarts=[windowNow.times.fajr,windowNow.times.dhuhr,windowNow.times.asr,windowNow.times.maghrib,windowNow.times.isha]; const prayerClocks=prayerStarts.map(minuteClockLabel); const slotIndex=live&&clock?windowNow.index:previewIndex; const baseSlot=slots[slotIndex]; const selectedDay=dayPeriod??slotIndex; const actualToday=clock??fallbackClock; const selectedJourneyDate=journeyDate??actualToday; const selectedPrayerTimes=getRiyadhPrayerTimes(selectedJourneyDate); const journeyPrayerStarts=[selectedPrayerTimes.fajr,selectedPrayerTimes.dhuhr,selectedPrayerTimes.asr,selectedPrayerTimes.maghrib,selectedPrayerTimes.isha];
 const riyadhDay=(value:Date|string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value));
 const calendarLocale=calendarMode==="islamic"?"ar-SA-u-ca-islamic-umalqura":"ar-SA-u-ca-gregory";
 const plannedJourney=useMemo(()=>slots.map((item,index)=>{const selectedKey=riyadhDay(selectedJourneyDate),todayKey=riyadhDay(actualToday),isToday=selectedKey===todayKey;const periodActivities=plan.filter(activity=>scheduledOn(activity,selectedJourneyDate)&&(activity.unitTracking?Boolean(unitPeriodFor(activity,item.period)):activity.nature==="goal"?activity.supportingPlan?.enabled&&activity.supportingPlan.period===item.period:activity.period===item.period));const dayAppointments=appointments.filter(appt=>appt.date===selectedKey&&appointmentPeriod(appt.time,journeyPrayerStarts)===index);const dayTasks=tasks.filter(task=>(task.date===selectedKey||(!task.date&&isToday))&&(task.time?appointmentPeriod(task.time,journeyPrayerStarts)===index:index===(isToday?slotIndex:0)));const activityTasks:JourneyTask[]=periodActivities.map(activity=>{const basePeriod=unitPeriodFor(activity,item.period),progress=unitProgress.find(value=>value.activityId===activity.id&&value.date===selectedKey),unitPeriod=basePeriod?{...basePeriod,target:progress?.targetByPeriod?.[basePeriod.id]??basePeriod.target}:undefined,completed=unitDone(progress,unitPeriod),remaining=unitPeriod?Math.max(0,unitPeriod.target-completed):0;return{name:activity.name,meta:unitPeriod?`${arNumber(remaining)} متبقٍ · ${unitPeriod.label.replace(/^بعد\s+/,"")}`:[activity.parentGoalId?"فعل مرتبط بهدف":"",activity.exercises?.length?`${arNumber(activity.exercises.length)} تمارين`:activity.quantity&&activity.unit?`${arNumber(activity.quantity)} ${activity.unit}`:"",durationLabel(activity.expectedMinutes)].filter(Boolean).join(" · "),done:unitPeriod?remaining===0:executionRecords.some(record=>record.activityId===activity.id&&riyadhDay(record.completedAt)===selectedKey),progress:unitPeriod?{done:completed,target:unitPeriod.target,percent:unitPeriod.target?Math.min(100,Math.round(completed/unitPeriod.target*100)):100}:undefined,kind:activity.parentGoalId?"goals":"commitments",activity}});return{period:item.period,totalMinutes:periodActivities.reduce((sum,activity)=>sum+activity.expectedMinutes,0),tasks:[...dayAppointments.map<JourneyTask>(appointment=>({name:appointment.title,meta:`موعد · ${arabicTime(appointment.time)}`,done:false,kind:"appointments",appointment})),...dayTasks.map<JourneyTask>(task=>({name:task.title,meta:task.time?`مهمة · ${arabicTime(task.time)}`:"مهمة اليوم",done:Boolean(task.completedAt),kind:"tasks",task})),...activityTasks]}}),[plan,tasks,appointments,executionRecords,unitProgress,selectedJourneyDate,actualToday,slotIndex]);
 const filteredJourney=useMemo(()=>plannedJourney.map(station=>{const visible=journeyFilter==="all"?station.tasks:station.tasks.filter(task=>task.kind===journeyFilter);return{...station,totalMinutes:visible.reduce((sum,task)=>sum+(task.activity?.expectedMinutes??0),0),tasks:visible}}),[plannedJourney,journeyFilter]);
 const currentTask=plannedJourney[slotIndex]?.tasks.find(task=>!task.done&&!(task as JourneyTask).appointment) as JourneyTask|undefined;
 const nearbyAppointment=plannedJourney[slotIndex]?.tasks.find(task=>(task as JourneyTask).appointment) as JourneyTask|undefined;
 const dueTask=tasks.find(task=>!task.completedAt&&(!task.date||task.date===riyadhDay(clock??fallbackClock))&&(!task.time||appointmentPeriod(task.time,prayerStarts)<=slotIndex));
 const actionActivity=currentTask?.activity??null;
 const actionMinutes=actionActivity?(actionActivity.nature==="goal"?(actionActivity.supportingPlan?.expectedMinutes??actionActivity.expectedMinutes):actionActivity.expectedMinutes):0;
 const availableMinutes=nearbyAppointment?.appointment?Math.max(0,timeToMinutes(nearbyAppointment.appointment.time)-((clock??fallbackClock).getHours()*60+(clock??fallbackClock).getMinutes())):windowNow.remainingMinutes;
 const suggestedMinutes=Math.max(1,Math.min(actionMinutes||windowNow.remainingMinutes,availableMinutes||windowNow.remainingMinutes)); const nextPeriod=windowNow.nextName==="الفجر"?"الصباح":windowNow.nextName;
 const slot={...baseSlot,hasAction:Boolean(actionActivity||dueTask),activity:dueTask?.title??currentTask?.name??(nearbyAppointment?nearbyAppointment.name:"لا شيء عليك الآن"),reading:!dueTask&&actionActivity?.template==="قراءة",minutes:suggestedMinutes,amount:dueTask?(dueTask.urgent?"مهمة مستعجلة · مرة واحدة":"مهمة · مرة واحدة"):nearbyAppointment&&!currentTask?nearbyAppointment.meta:(currentTask?.meta||"هذه المحطة لك."),note:dueTask?"أنجزها وأخرجها من رأسك.":nearbyAppointment?`لديك ${nearbyAppointment.name} عند ${arabicTime(nearbyAppointment.appointment!.time)}. تركنا له مكانًا.`:(currentTask?"هذا هو الفعل الآن. والباقي ينتظر.":"ليس مطلوبًا أن تملأ كل دقيقة."),next:`${nextPeriod} بعد ${durationLabel(windowNow.remainingMinutes)}`}; const [seconds,setSeconds]=useState(baseSlot.minutes*60);
 useEffect(()=>{const records=readExecutionLog();setClock(new Date());setPlan(readPlan());setTasks(readTasks());setAppointments(readAppointments());setUnitProgress(readUnitProgress());setExecutionRecords(records);setSavedCount(records.length);setCalendarMode(localStorage.getItem("sair.calendar.v1")==="islamic"?"islamic":"gregory");const storedFilter=localStorage.getItem("sair.journeyFilter.v1") as JourneyFilter|null;if(storedFilter&&["all","goals","commitments","tasks","appointments"].includes(storedFilter))setJourneyFilter(storedFilter);const t=window.setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(t)},[]);
 const changeJourneyFilter=(filter:JourneyFilter)=>{setJourneyFilter(filter);localStorage.setItem("sair.journeyFilter.v1",filter)};
 const changeCalendar=(mode:"islamic"|"gregory")=>{setCalendarMode(mode);localStorage.setItem("sair.calendar.v1",mode)};
 useEffect(()=>{if(phase!=="running")return;const t=window.setInterval(()=>setSeconds(v=>v>0?v-1:0),1000);return()=>clearInterval(t)},[phase]);
 useEffect(()=>{if(seconds===0&&phase==="running")setPhase("done")},[seconds,phase]);
 const elapsed=useMemo(()=>Math.max(0,slot.minutes*60-seconds),[seconds,slot.minutes]);
 const reset=(i=slotIndex,isLive=false)=>{setPreviewIndex(i);setLive(isLive);setPhase("idle");setSeconds(slots[i].minutes*60);setPages(0)};
 const recordExecution=(record:ExecutionRecord)=>{setSavedCount(saveExecution(record));setExecutionRecords(readExecutionLog())};
 const finish=()=>{const minutes=Math.max(1,Math.round(elapsed/60));recordExecution({activityId:runningActivity?.id,activity:slot.activity,minutes,quantity:slot.reading?pages:undefined,quantityUnit:slot.reading?"صفحة":undefined,completedAt:new Date().toISOString(),status:"completed"});setPhase("done")};
 const startCurrent=()=>{setSeconds(slot.minutes*60);setPages(0);setPhase("running")};
 const startTask=(activity?:PlannedActivity)=>{if(!activity)return;setViewMotion("forward");window.setTimeout(()=>setViewMotion(null),420);setRunningActivity(activity);setTab("now");if(activity.unitTracking){setActiveDhikr(activity);return}if(activity.template==="رياضة"&&activity.exercises?.length){setActiveWorkout(activity);return}setSeconds((activity.nature==="goal"?(activity.supportingPlan?.expectedMinutes??activity.expectedMinutes):activity.expectedMinutes)*60);setPhase("running")};
 const returnToJourney=()=>{setViewMotion("back");window.setTimeout(()=>{setActiveWorkout(null);setActiveDhikr(null);setPhase("idle")},220);window.setTimeout(()=>setViewMotion(null),520)};
 const openJourneyTask=(task:JourneyTask)=>{if(task.appointment){openAppointment(task.appointment);return}if(task.task){openTask(task.task);return}if(task.activity)startTask(task.activity)};
 const openActivity=(activity:PlannedActivity|null,nature:"goal"|"commitment"=activity?.nature??"commitment")=>{setCreationNature(nature);setEditingActivity(activity);window.setTimeout(()=>$("add-sheet")?.showModal(),0)};
 const saveActivity=(activity:PlannedActivity)=>{if(editingActivity){setPlan(updatePlan(activity));return}if(activity.nature==="goal"&&activity.supportingPlan){const commitmentId=`commitment-${activity.id}`;const goal={...activity,linkedCommitmentId:commitmentId,supportingPlan:{...activity.supportingPlan,enabled:false}};const commitment:PlannedActivity={id:commitmentId,nature:"commitment",parentGoalId:activity.id,name:activity.supportingPlan.actionName,template:activity.template,period:activity.supportingPlan.period,goal:`يقود إلى ${activity.name}`,expectedMinutes:activity.supportingPlan.expectedMinutes,schedule:activity.supportingPlan.schedule,quantity:activity.quantity,unit:activity.unit,measurements:activity.measurements,exercises:activity.exercises,reminder:{mode:"station",value:activity.supportingPlan.period}};savePlan(goal);setPlan(savePlan(commitment));return}setPlan(savePlan(activity))};
 const openTask=(item:TaskItem|null)=>{setEditingTask(item);window.setTimeout(()=>$("task-sheet")?.showModal(),0)};
 const openAppointment=(item:Appointment|null)=>{setEditingAppointment(item);window.setTimeout(()=>$("appointment-sheet")?.showModal(),0)};
 const completeTask=(item:TaskItem)=>setTasks(updateTask({...item,completedAt:item.completedAt?undefined:new Date().toISOString()}));
 const prayerActivity=plan.find(item=>item.name.includes("الصلاة"));
 return <main className={`app-shell tone-${slotIndex}`} dir="rtl">
  <header className="topbar"><button className="profile-trigger" aria-label="فتح منطقة أنت" onClick={()=>setDrawerOpen(true)}>أ</button>{tab==="now"&&phase==="idle"&&!activeWorkout&&!activeDhikr?<button className="time-trigger" onClick={()=>$("time-sheet")?.showModal()}><i/>{live?(clock?clockLabel(clock):"الوقت الفعلي"):slot.time}<span>⌄</span></button>:<b className="top-brand">سائر</b>}</header>
  {tab==="now"&&activeWorkout&&<div className={`activity-page ${viewMotion==="back"?"slide-out-right":"slide-in-left"}`}><WorkoutRunner activity={activeWorkout} onExit={returnToJourney} onFinish={(minutes,repetitions)=>{recordExecution({activityId:activeWorkout.id,activity:activeWorkout.name,minutes,quantity:repetitions,quantityUnit:"عدة",completedAt:new Date().toISOString(),status:"completed"});returnToJourney()}}/></div>}
  {tab==="now"&&activeDhikr&&<div className={`activity-page ${viewMotion==="back"?"slide-out-right":"slide-in-left"}`}><DhikrRunner activity={activeDhikr} date={riyadhDay(clock??new Date())} initial={unitProgress.find(item=>item.activityId===activeDhikr.id&&item.date===riyadhDay(clock??new Date()))} onExit={returnToJourney} onEdit={()=>openActivity(activeDhikr,"commitment")} onChange={progress=>setUnitProgress(saveUnitProgress(progress))} onFinish={total=>{const dueKey=riyadhDay(clock??new Date());if(!executionRecords.some(record=>record.activityId===activeDhikr.id&&record.dueKey===dueKey))recordExecution({activityId:activeDhikr.id,activity:activeDhikr.name,minutes:0,quantity:total,quantityUnit:"ذكر",completedAt:new Date().toISOString(),status:"completed",dueKey})}}/></div>}
  {tab==="now"&&!activeWorkout&&!activeDhikr&&(phase==="idle"?<div className={viewMotion==="back"?"journey-page slide-in-right":"journey-page"}><JourneyFilters value={journeyFilter} onChange={changeJourneyFilter}/><DayJourney journey={filteredJourney} selected={selectedDay} current={slotIndex} today={actualToday} activeDate={selectedJourneyDate} calendarMode={calendarMode} remaining={windowNow.remainingMinutes} remainingSeconds={Math.max(0,windowNow.remainingMinutes*60-(clock?.getSeconds()??0))} prayerStarts={journeyPrayerStarts} onDateChange={date=>{setJourneyDate(date);setDayPeriod(riyadhDay(date)===riyadhDay(actualToday)?slotIndex:0)}} onSelect={setDayPeriod} onOpen={openJourneyTask}/></div>:<div className={`activity-page ${viewMotion==="back"?"slide-out-right":"slide-in-left"}`}><Now slot={slot} phase={phase} seconds={seconds} pages={pages} elapsed={elapsed} fits={fitsWindow(slot.minutes,windowNow.remainingMinutes)} live={live} setPhase={setPhase} setPages={setPages} finish={finish} returnToJourney={returnToJourney} start={()=>dueTask?completeTask(dueTask):actionActivity&&startTask(actionActivity)}/></div>)}
  {tab!=="now"&&<SectionScreen key={tab} kind={tab as SectionKind} plan={plan} tasks={tasks} appointments={appointments} records={executionRecords} onEditActivity={item=>openActivity(item,tab==="goals"?"goal":"commitment")} onStartActivity={startTask} onEditTask={openTask} onEditAppointment={openAppointment} onCompleteTask={completeTask} onQuickPrayer={()=>$("prayer-sheet")?.showModal()}/>}
  <nav className="bottom-nav">{nav.map(n=><button key={n.id} className={`${tab===n.id?"active":""} ${n.id==="now"?"nav-now":""}`} onClick={()=>{setTab(n.id);if(n.id!=="now"){setActiveWorkout(null);setActiveDhikr(null)}}}><span>{n.icon}</span>{n.label}</button>)}</nav>
  <ProfileDrawer open={drawerOpen} onClose={()=>setDrawerOpen(false)} calendarMode={calendarMode} onCalendarChange={changeCalendar} settings={settings}/>
  <TimeSheet live={live} clock={clock} slotIndex={slotIndex} prayerClocks={prayerClocks} reset={reset} setClock={setClock}/>
  <AddActivitySheet editing={editingActivity} forcedNature={creationNature} onSave={saveActivity} onDelete={id=>{setPlan(deletePlan(id));setEditingActivity(null)}}/>
  <TaskDialog editing={editingTask} onSave={item=>setTasks(editingTask?updateTask(item):saveTask(item))} onDelete={id=>{setTasks(deleteTask(id));setEditingTask(null)}}/>
  <AppointmentSheet editing={editingAppointment} onSave={item=>setAppointments(editingAppointment?updateAppointment(item):saveAppointment(item))} onDelete={id=>{setAppointments(deleteAppointment(id));setEditingAppointment(null)}}/>
  <dialog id="sport-sheet" className="sheet detail"><SheetHead kicker="رياضة · العصر" title="تمارين مقاومة"/><div className="detail-meta"><span>٤ جلسات أسبوعيًا</span><span>٣٥ دقيقة</span><span>وقت + جلسات + تكرارات</span></div><div className="exercise-list">{activities[1].items?.map(x=><div key={x.name}><b>{x.name}</b><span>{arNumber(x.sets)} جلسات × {arNumber(x.reps)} تكرارًا</span></div>)}</div><div className="result"><small>نتيجة جلسة سابقة</small><b>٣٢ دقيقة</b><span>١٠ جلسات · ١١٢ تكرارًا</span></div></dialog>
  <dialog id="prayer-sheet" className="sheet"><SheetHead kicker="تسجيل سريع" title="الصلاة مع الجماعة"/><p className="sheet-copy">كيف أدركت الصلاة؟ ضغطة واحدة تكفي.</p><div className="prayer-options">{activities[3].completionStates?.map(s=><button className={prayer===s?"selected":""} key={s} onClick={()=>{setPrayer(s);recordExecution({activityId:prayerActivity?.id,activity:prayerActivity?.name??"الصلاة مع الجماعة",minutes:0,quantityUnit:s,completedAt:new Date().toISOString(),status:s==="فاتتني الجماعة"?"missed":"completed"})}}>{s}<span>{prayer===s?"✓":""}</span></button>)}</div>{prayer&&<p className="recorded">سُجلت: {prayer}</p>}</dialog>
 </main>
}

const $=(id:string)=>document.getElementById(id) as HTMLDialogElement|null;
function AfterNow({journey,tasks,appointments,current}:{journey:JourneyStation[];tasks:TaskItem[];appointments:Appointment[];current:number}){
 const nextActivities=journey.slice(current).flatMap(station=>station.tasks.map(task=>({...task,period:station.period}))).filter(task=>!task.done).slice(0,4);
 const pendingTasks=tasks.filter(task=>!task.completedAt).slice(0,2).map(task=>({name:task.title,meta:task.time?`مهمة · ${arabicTime(task.time)}`:"مهمة",period:"اليوم"}));
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const upcomingAppointments=appointments.filter(item=>item.date===today).slice(0,2).map(item=>({name:item.title,meta:`موعد · ${arabicTime(item.time)}`,period:"اليوم"}));
 const next=[...nextActivities,...pendingTasks,...upcomingAppointments].filter((item,index,array)=>array.findIndex(x=>x.name===item.name&&x.meta===item.meta)===index).slice(0,5);
 return <section className="after-now"><header><h2>بعد ذلك</h2><span>بقية يومك، بهدوء</span></header>{next.length?<div>{next.map((item,index)=><article key={`${item.name}-${index}`}><i>{arNumber(index+1)}</i><section><b>{item.name}</b><span>{item.period} · {item.meta}</span></section></article>)}</div>:<p>لا شيء ينتظرك. وهذه نتيجة جيدة أيضًا.</p>}</section>
}
function PlanScreen({plan,appointments,openActivity,openAppointment}:{plan:PlannedActivity[];appointments:Appointment[];openActivity:(item:PlannedActivity|null)=>void;openAppointment:(item:Appointment|null)=>void}){
 const goals=plan.filter(item=>item.nature==="goal"),commitments=plan.filter(item=>item.nature!=="goal");
 const group=(title:string,subtitle:string,items:PlannedActivity[])=><section className="plan-group"><div className="plan-group-title"><h2>{title}</h2><span>{arNumber(items.length)}</span></div><p>{subtitle}</p>{items.length?<div className="activity-list">{items.map(item=><button key={item.id} onClick={()=>openActivity(item)}><span className="activity-icon">{item.template[0]}</span><div><h3>{item.name}</h3><p>{item.nature==="goal"?goalSummary(item):`${item.period} · ${item.schedule.value}`}</p></div><span>‹</span></button>)}</div>:<div className="empty-inline">لا شيء هنا بعد.</div>}</section>;
 return <section className="screen"><Head kicker="ما اخترته لحياتك" title="الخطة" text="أهداف تتقدم نحوها، والتزامات تحافظ عليها، ومواعيد تجد مكانها في يومك."/><button className="primary add" onClick={()=>openActivity(null)}>+ إضافة إلى خطتي</button>{group("الأهداف","نقيس المسافة بين حالك الآن وما تريد الوصول إليه.",goals)}{group("الالتزامات","نقيس أداء الاستحقاقات، دون ترحيل الفائت.",commitments)}<section className="plan-group"><div className="plan-group-title"><h2>المواعيد</h2><span>{arNumber(appointments.length)}</span></div><p>تظهر في يومها وتحجز مكانها من المحطة.</p>{appointments.length?<div className="activity-list">{appointments.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(item=><button key={item.id} onClick={()=>openAppointment(item)}><span className="activity-icon">م</span><div><h3>{item.title}</h3><p>{item.date} · {arabicTime(item.time)}</p></div><span>‹</span></button>)}</div>:<div className="empty-inline">لا مواعيد قريبة.</div>}</section></section>
}
function goalSummary(item:PlannedActivity){const goal=item.goalDefinition;if(!goal)return "هدف تطويري";if(goal.kind==="level")return `${goal.currentLevel||"—"} ← ${goal.targetLevel||"—"}`;return `${arNumber(goal.currentValue??goal.currentMilestone??0)} / ${arNumber(goal.targetValue??goal.targetMilestone??0)} ${goal.unit??""}`}
function AppointmentSheet({editing,onSave,onDelete}:{editing:Appointment|null;onSave:(item:Appointment)=>void;onDelete:(id:string)=>void}){
 const [title,setTitle]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[alert,setAlert]=useState("30");
 useEffect(()=>{setTitle(editing?.title??"");setDate(editing?.date??new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()));setTime(editing?.time??"16:30");setAlert(String(editing?.alertMinutes??30))},[editing]);
 const close=()=>$("appointment-sheet")?.close();
 return <dialog id="appointment-sheet" className="sheet activity-wizard"><SheetHead kicker={editing?"تعديل":"موعد جديد"} title="متى يحتاج أن يجد مكانه؟"/><div className="wizard-body"><label>ما الموعد؟<input value={title} onChange={event=>setTitle(event.target.value)} placeholder="مثال: موعد الطبيب"/></label><div className="split-fields"><label>اليوم<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>الوقت<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div><label>التنبيه<select value={alert} onChange={event=>setAlert(event.target.value)}><option value="0">عند الموعد</option><option value="15">قبل ١٥ دقيقة</option><option value="30">قبل ٣٠ دقيقة</option><option value="60">قبل ساعة</option></select></label></div><div className="wizard-actions"><button className="primary" disabled={!title.trim()||!date||!time} onClick={()=>{onSave({id:editing?.id??`appointment-${Date.now()}`,title:title.trim(),date,time,alertMinutes:Number(alert)});close()}}>{editing?"حفظ التعديلات":"أضف الموعد"}</button></div>{editing&&<button className="delete-activity" onClick={()=>{onDelete(editing.id);close()}}>حذف الموعد</button>}</dialog>
}
function TimeSheet({live,clock,slotIndex,prayerClocks,reset,setClock}:{live:boolean;clock:Date|null;slotIndex:number;prayerClocks:string[];reset:(index:number,isLive?:boolean)=>void;setClock:(date:Date)=>void}){
 return <dialog id="time-sheet" className="sheet"><SheetHead kicker="أداة النموذج" title="اختر محطة زمنية"/><div className="time-options"><button className={live?"selected live-time":"live-time"} onClick={()=>{const now=new Date();reset(resolveTimeWindow(now).index,true);setClock(now);$("time-sheet")?.close()}}><span>الوقت الفعلي · الرياض</span><b>{clock?clockLabel(clock):"—"}</b></button>{slots.map((item,index)=><button key={item.period} className={!live&&index===slotIndex?"selected":""} onClick={()=>{reset(index);$("time-sheet")?.close()}}><span>{item.period}</span><b>{prayerClocks[index]}</b></button>)}</div><p className="prototype-note">المحطات مرتبطة بحساب مواقيت الصلاة في الرياض، وتتجدد يوميًا دون اتصال خارجي.</p></dialog>
}
const weekDays=["السبت","الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة"];
const initialActivity={nature:"" as ""|"goal"|"commitment",template:"",name:"",period:"العصر",scheduleMode:"fixed" as "daily"|"fixed"|"flexible",scheduleValue:"",days:[] as string[],goal:"",quantity:"",unit:"",expectedMinutes:"20",startTime:"",endTime:"",goalKind:"quantity" as "quantity"|"level"|"milestone",currentValue:"",targetValue:"",currentLevel:"",targetLevel:"",actionName:""};
const initialUnitPeriods:UnitPeriod[]=[{id:"dhikr-0",label:"بعد العصر",period:"العصر",target:1000,unitCount:10,unitValue:100}];
function AddActivitySheet({editing,forcedNature,onSave,onDelete}:{editing:PlannedActivity|null;forcedNature:"goal"|"commitment";onSave:(activity:PlannedActivity)=>void;onDelete:(id:string)=>void}){
 const [step,setStep]=useState(1),[form,setForm]=useState(initialActivity),[showDuration,setShowDuration]=useState(false),[exercises,setExercises]=useState<WorkoutExercise[]>([]),[dhikrMethod,setDhikrMethod]=useState<"counter"|"units">("counter"),[dhikrPress,setDhikrPress]=useState(1),[dhikrSplit,setDhikrSplit]=useState(false),[dhikrPeriods,setDhikrPeriods]=useState<UnitPeriod[]>(initialUnitPeriods);
 useEffect(()=>{if(!editing){setForm({...initialActivity,nature:forcedNature});setExercises([]);setDhikrMethod("counter");setDhikrPress(1);setDhikrSplit(false);setDhikrPeriods(initialUnitPeriods);setStep(2);return}const days=editing.schedule.mode==="daily"?weekDays:(editing.schedule.days?.length?editing.schedule.days:weekDays.filter(day=>editing.schedule.value.includes(day)));setForm({...initialActivity,nature:editing.nature??forcedNature,template:editing.template,name:editing.name,period:editing.period,scheduleMode:editing.schedule.mode,scheduleValue:editing.schedule.value,days,goal:editing.goal,quantity:editing.quantity?.toString()??editing.unitTracking?.target.toString()??"",unit:editing.unit??editing.goalDefinition?.unit??"",expectedMinutes:editing.expectedMinutes.toString(),startTime:editing.startTime??"",endTime:editing.endTime??"",goalKind:editing.goalDefinition?.kind??"quantity",currentValue:editing.goalDefinition?.currentValue?.toString()??editing.goalDefinition?.currentMilestone?.toString()??"",targetValue:editing.goalDefinition?.targetValue?.toString()??editing.goalDefinition?.targetMilestone?.toString()??"",currentLevel:editing.goalDefinition?.currentLevel??"",targetLevel:editing.goalDefinition?.targetLevel??"",actionName:editing.supportingPlan?.actionName??""});setExercises(editing.exercises?.map(item=>({...item}))??[]);setDhikrMethod(editing.unitTracking?.method??"counter");setDhikrPress(editing.unitTracking?.pressValue??1);setDhikrSplit((editing.unitTracking?.periods.length??0)>1);setDhikrPeriods(editing.unitTracking?.periods?.map(item=>({...item}))??initialUnitPeriods);setStep(2)},[editing,forcedNature]);
 const update=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
 const templateMeasurements:Record<string,string[]>={"رياضة":["الوقت","الجلسات","التكرارات"],"قراءة":["الوقت","الصفحات"],"ذكر واستغفار":["الوحدات"],"نوم":["فترة بين وقتين"],"صيام":["فترة بين وقتين"],"عادة":["تم / لم يتم"],"مهارة":["الوقت","الجلسات"],"شيء آخر":["الوقت"]};
 const suggestedUnit=form.nature==="goal"?form.unit:form.template==="قراءة"?"صفحات":form.template==="رياضة"?"تكرارات":form.template==="مهارة"?"جلسات":form.unit;
 const daysLabel=(days:string[])=>days.length===7?"جميع الأيام":days.join("، ");
 const toggleDay=(day:string)=>setForm(current=>{const days=current.days.includes(day)?current.days.filter(item=>item!==day):[...current.days,day];return{...current,days,scheduleMode:days.length===7?"daily":"fixed",scheduleValue:daysLabel(days)}});
 const toggleAllDays=()=>setForm(current=>{const days=current.days.length===7?[]:weekDays;return{...current,days,scheduleMode:days.length===7?"daily":"fixed",scheduleValue:daysLabel(days)}});
 const close=()=>{$("add-sheet")?.close();setStep(2);setShowDuration(false);if(!editing){setExercises([]);setDhikrPeriods(initialUnitPeriods);setForm({...initialActivity,nature:forcedNature})}};
 const isSport=form.template==="رياضة";
 const isDhikr=form.template==="ذكر واستغفار"&&form.nature==="commitment";
 const updateDhikrPeriod=(id:string,key:keyof UnitPeriod,value:string|number)=>setDhikrPeriods(current=>current.map(item=>item.id===id?{...item,[key]:value,...(key==="period"?{label:`بعد ${value}`}:{})}:item).map(item=>({...item,target:item.unitCount*item.unitValue})));
 const addDhikrPeriod=()=>setDhikrPeriods(current=>[...current,{id:`dhikr-${Date.now()}`,label:"بعد المغرب",period:"المغرب",target:1000,unitCount:10,unitValue:100}]);
 const dhikrTarget=(dhikrSplit?dhikrPeriods:[{...dhikrPeriods[0],period:form.period,label:`بعد ${form.period}`,target:Number(form.quantity)||dhikrPeriods[0].target}]).reduce((sum,item)=>sum+item.target,0);
 const toggleExercise=(exercise:WorkoutExercise)=>setExercises(current=>current.some(item=>item.id===exercise.id)?current.filter(item=>item.id!==exercise.id):[...current,{...exercise}]);
 const updateExercise=(id:string,key:keyof WorkoutExercise,value:number)=>setExercises(current=>current.map(item=>item.id===id?{...item,[key]:value}:item));
 const submit=()=>{const schedule={mode:form.scheduleMode,value:form.scheduleValue||"غير محدد",days:form.days};const configuredPeriods=dhikrSplit?dhikrPeriods:[{...dhikrPeriods[0],period:form.period,label:`بعد ${form.period}`,target:Number(form.quantity)||dhikrPeriods[0].target,unitCount:dhikrMethod==="units"?dhikrPeriods[0].unitCount:Math.max(1,Math.ceil((Number(form.quantity)||dhikrPeriods[0].target)/Math.max(1,dhikrPress))),unitValue:dhikrMethod==="units"?dhikrPeriods[0].unitValue:dhikrPress}];onSave({id:editing?.id??`activity-${Date.now()}`,nature:form.nature||"commitment",name:form.name.trim(),template:form.template,period:isDhikr?configuredPeriods[0].period:form.period,goal:form.goal.trim(),expectedMinutes:Math.max(0,Number(form.expectedMinutes)||0),schedule,quantity:isDhikr?dhikrTarget:form.quantity?Number(form.quantity):undefined,unit:isDhikr?"ذكر":suggestedUnit||undefined,measurements:templateMeasurements[form.template]??["الوقت"],startTime:form.startTime||undefined,endTime:form.endTime||undefined,exercises:isSport?exercises:undefined,unitTracking:isDhikr?{method:dhikrMethod,target:dhikrTarget,pressValue:Math.max(1,dhikrPress),periods:configuredPeriods}:undefined,goalDefinition:form.nature==="goal"?{kind:form.goalKind,currentValue:form.goalKind!=="level"?Number(form.currentValue)||0:undefined,targetValue:form.goalKind==="quantity"?Number(form.targetValue)||0:undefined,unit:suggestedUnit||undefined,currentLevel:form.goalKind==="level"?form.currentLevel:undefined,targetLevel:form.goalKind==="level"?form.targetLevel:undefined,currentMilestone:form.goalKind==="milestone"?Number(form.currentValue)||0:undefined,targetMilestone:form.goalKind==="milestone"?Number(form.targetValue)||1:undefined}:undefined,supportingPlan:form.nature==="goal"?{enabled:true,actionName:form.actionName.trim()||form.template,expectedMinutes:Number(form.expectedMinutes)||20,schedule,period:form.period}:undefined});close()};
 const canContinue=step===1?Boolean(form.nature):step===2?Boolean(form.template&&form.name.trim()):isSport&&step===4?exercises.length>0:isDhikr&&step===4?dhikrTarget>0&&dhikrPeriods.every(item=>item.unitCount>0&&item.unitValue>0):form.nature==="goal"&&step===3?Boolean((form.goalKind==="level"?form.currentLevel&&form.targetLevel:form.targetValue)&&form.actionName.trim()&&form.days.length):true;
 const totalSteps=isSport?6:5,measureStep=isSport?5:4,reviewStep=isSport?6:5;
 const titles=isSport?["ماذا تريد أن تضيف؟","ما المجال؟","كيف نقيس التقدم؟","اختر تمارين الجلسة","متى يجد الفعل مكانه؟","راجع خطتك"]:["ماذا تريد أن تضيف؟","ما المجال؟","كيف نقيس النجاح؟","متى يجد الفعل مكانه؟","راجع خطتك"];
 return <dialog id="add-sheet" className="sheet activity-wizard"><div className="wizard-head"><div><p>{editing?"تعديل النشاط":"نشاط جديد"} · {arNumber(step)} من {arNumber(totalSteps)}</p><h2>{titles[step-1]}</h2></div><button aria-label="إغلاق" onClick={close}>×</button></div><div className="wizard-progress"><span style={{width:`${step*(100/totalSteps)}%`}}/></div>
  {step===1&&<div className="wizard-body kind-choices"><button className={form.nature==="goal"?"selected":""} onClick={()=>update("nature","goal")}><b>هدف</b><span>شيء تريد التقدم نحوه والوصول إليه.</span></button><button className={form.nature==="commitment"?"selected":""} onClick={()=>update("nature","commitment")}><b>التزام</b><span>شيء تريد المحافظة عليه وقياس انتظامك فيه.</span></button>{!editing&&<button onClick={()=>{$("add-sheet")?.close();$("appointment-sheet")?.showModal()}}><b>موعد</b><span>شيء مرتبط بيوم أو وقت محدد.</span></button>}</div>}
  {step===2&&<div className="wizard-body"><label>{form.nature==="goal"?"ما الذي تريد أن تصل إليه؟":"ما الذي تريد أن تحافظ عليه؟"}<input value={form.name} onChange={event=>update("name",event.target.value)} placeholder={form.template==="ذكر واستغفار"?"اكتب الذكر أو اختر مثالًا أدناه":form.nature==="goal"?"مثال: الجري ١٠ كم دون توقف":"مثال: أتمرن ٣ مرات أسبوعيًا"}/></label>{form.template==="ذكر واستغفار"&&<div className="dhikr-presets">{["الاستغفار","التسبيح","التهليل","الصلاة على النبي ﷺ"].map(name=><button type="button" key={name} className={form.name===name?"selected":""} onClick={()=>update("name",name)}>{name}</button>)}</div>}<div className="field-label">اختر المجال</div><div className="templates">{templates.map(template=><button type="button" key={template} className={form.template===template?"selected":""} onClick={()=>update("template",template)}><span>{template}</span><i>{form.template===template?"✓":"+"}</i></button>)}</div></div>}
  {step===3&&form.nature==="goal"&&<div className="wizard-body"><div className="field-label">كيف يظهر التقدم؟</div><div className="goal-kind-row">{[["quantity","كمية"],["level","مستوى"],["milestone","موضع إنجاز"]].map(([key,label])=><button key={key} className={form.goalKind===key?"selected":""} onClick={()=>update("goalKind",key)}>{label}</button>)}</div>{form.goalKind==="level"?<div className="split-fields"><label>المستوى الحالي<input value={form.currentLevel} onChange={e=>update("currentLevel",e.target.value)} placeholder="B1"/></label><label>المستوى المستهدف<input value={form.targetLevel} onChange={e=>update("targetLevel",e.target.value)} placeholder="B2"/></label></div>:<div className="split-fields"><label>الحالي<input inputMode="decimal" value={form.currentValue} onChange={e=>update("currentValue",e.target.value)} placeholder="٠"/></label><label>المستهدف<input inputMode="decimal" value={form.targetValue} onChange={e=>update("targetValue",e.target.value)} placeholder="٢٤"/></label></div>}<label>وحدة القياس<input value={form.unit} onChange={e=>update("unit",e.target.value)} placeholder="كتاب، كم، مرحلة…"/></label><label>الفعل الذي يدفعك نحوه<input value={form.actionName} onChange={e=>update("actionName",e.target.value)} placeholder="مثال: قراءة ٣٠ دقيقة"/></label><div className="field-label">متى يجد هذا الفعل مكانه؟</div><div className="choice-row">{["الصباح","الظهر","العصر","المغرب","الليل"].map(period=><button className={form.period===period?"selected":""} key={period} onClick={()=>update("period",period)}>{period}</button>)}</div><div className="week-days">{weekDays.map(day=><button className={form.days.includes(day)?"selected":""} key={day} onClick={()=>toggleDay(day)}><span>{day}</span></button>)}</div></div>}
  {step===3&&form.nature==="commitment"&&<div className="wizard-body"><div className="measure-note">سنقيس الاستحقاقات المنجزة، لا نجمع الفائت على يوم جديد.</div><div className="field-label">في أي فترة؟</div><div className="choice-row">{["الصباح","الظهر","العصر","المغرب","الليل"].map(period=><button className={form.period===period?"selected":""} key={period} onClick={()=>update("period",period)}>{period}</button>)}</div><div className="field-label repeat-title"><span>كيف يتكرر؟</span><button className={form.days.length===7?"selected":""} onClick={toggleAllDays}><b>∞</b> جميع الأيام</button></div><div className="week-days">{weekDays.map(day=><button className={form.days.includes(day)?"selected":""} key={day} onClick={()=>toggleDay(day)}><span>{day}</span></button>)}</div><label>لماذا تريد المحافظة عليه؟ <small>اختياري</small><input value={form.goal} onChange={event=>update("goal",event.target.value)} placeholder="ما الذي يجعله مهمًا؟"/></label></div>}
  {isSport&&step===4&&<div className="wizard-body exercise-builder"><p className="builder-note">اختر ما ستؤديه فعلًا. يمكنك ضبط كل تمرين بعد إضافته.</p>{["دفع","سحب","أرجل","جذع"].map(category=><section key={category}><h3>{category}</h3><div className="exercise-choices">{calisthenicsCatalog.filter(item=>item.category===category).map(item=><button key={item.id} className={exercises.some(x=>x.id===item.id)?"selected":""} onClick={()=>toggleExercise(item)}><span>{item.name}</span><b>{exercises.some(x=>x.id===item.id)?"✓":"+"}</b></button>)}</div></section>)}{exercises.length>0&&<div className="selected-exercises">{exercises.map(item=><article key={item.id}><div><h4>{item.name}</h4><span>{item.measurement==="duration"?"تمرين زمني":"تمرين بالعدات"}</span></div><label>الجولات<input type="number" min="1" max="10" value={item.sets} onChange={event=>updateExercise(item.id,"sets",Number(event.target.value))}/></label>{item.measurement==="duration"?<label>الثواني<input type="number" min="5" value={item.durationSeconds} onChange={event=>updateExercise(item.id,"durationSeconds",Number(event.target.value))}/></label>:<label>العدات<input type="number" min="1" value={item.reps} onChange={event=>updateExercise(item.id,"reps",Number(event.target.value))}/></label>}<label>الراحة<input type="number" min="0" step="15" value={item.restSeconds} onChange={event=>updateExercise(item.id,"restSeconds",Number(event.target.value))}/><small>ث</small></label></article>)}</div>}</div>}
  {isDhikr&&step===measureStep&&<div className="wizard-body dhikr-config"><div className="measure-note">طريقة القياس العامة: وحدات. اختر كيف تريد تنفيذها اليوم.</div><div className="dhikr-mode-row"><button className={dhikrMethod==="counter"?"selected":""} onClick={()=>setDhikrMethod("counter")}>عداد مباشر</button><button className={dhikrMethod==="units"?"selected":""} onClick={()=>setDhikrMethod("units")}>وحدات مرئية</button></div>{dhikrMethod==="counter"&&<><label>العدد المطلوب يوميًا<input type="number" min="1" value={form.quantity||dhikrPeriods[0].target} onChange={event=>update("quantity",event.target.value)}/></label><label>قيمة كل ضغطة<input type="number" min="1" value={dhikrPress} onChange={event=>setDhikrPress(Math.max(1,Number(event.target.value)||1))}/></label><div className="dhikr-presets">{[1,10,100].map(value=><button type="button" className={dhikrPress===value?"selected":""} key={value} onClick={()=>setDhikrPress(value)}>+{arNumber(value)}</button>)}</div></>}<label className="dhikr-split-toggle"><input type="checkbox" checked={dhikrSplit} onChange={event=>setDhikrSplit(event.target.checked)}/> تقسيم الورد على فترات اليوم</label>{(dhikrSplit||dhikrMethod==="units")&&<>{(dhikrSplit?dhikrPeriods:dhikrPeriods.slice(0,1)).map((item,index)=><section className="dhikr-period-config" key={item.id}><div><label>الفترة<select value={item.period} onChange={event=>updateDhikrPeriod(item.id,"period",event.target.value)}>{["الصباح","الظهر","العصر","المغرب","الليل"].map(period=><option key={period}>{period}</option>)}</select></label><label>الوحدات<input type="number" min="1" value={item.unitCount} onChange={event=>updateDhikrPeriod(item.id,"unitCount",Math.max(1,Number(event.target.value)||1))}/></label><label>قيمة الوحدة<input type="number" min="1" value={item.unitValue} onChange={event=>updateDhikrPeriod(item.id,"unitValue",Math.max(1,Number(event.target.value)||1))}/></label></div>{dhikrSplit&&dhikrPeriods.length>1&&<button onClick={()=>setDhikrPeriods(current=>current.filter(period=>period.id!==item.id))}>حذف الفترة</button>}{index===0&&!dhikrSplit&&<p className="preview-note">{arNumber(item.unitCount)} × {arNumber(item.unitValue)} = {arNumber(item.target)}</p>}</section>)}{dhikrSplit&&<button className="wizard-back" type="button" onClick={addDhikrPeriod}>+ إضافة فترة</button>}<div className="dhikr-total"><span>إجمالي ورد اليوم</span><b>{arNumber(dhikrTarget)}</b></div></>}<div className="duration-picker"><button type="button" onClick={()=>setShowDuration(value=>!value)}><span>المدة المتوقعة</span><b>{arNumber(Number(form.expectedMinutes)||0)} دقيقة</b><i>{showDuration?"⌃":"⌄"}</i></button>{showDuration&&<div className="duration-slider"><input type="range" min="5" max="120" step="5" value={form.expectedMinutes} onChange={event=>update("expectedMinutes",event.target.value)}/></div>}</div></div>}
  {!isDhikr&&step===measureStep&&<div className="wizard-body">{["نوم","صيام"].includes(form.template)?<div className="time-range"><label>يبدأ<input type="time" value={form.startTime} onChange={event=>update("startTime",event.target.value)}/></label><label>ينتهي<input type="time" value={form.endTime} onChange={event=>update("endTime",event.target.value)}/></label></div>:<><div className="measure-note">سيُقاس بـ: {(templateMeasurements[form.template]??["الوقت"]).join(" + ")}</div>{!isSport&&<div className="split-fields"><label>الوحدة<select value={suggestedUnit} onChange={event=>update("unit",event.target.value)}><option value="">اختر الوحدة</option>{["صفحة","عدة","مرة","تكرار","جلسة","دقيقة","ساعة","متر","كيلومتر","خطوة","كوب","عنصر"].map(unit=><option key={unit} value={unit}>{unit}</option>)}</select></label><label>الكمية<input inputMode="decimal" value={form.quantity} onChange={event=>update("quantity",event.target.value)} placeholder="٥"/></label></div>}</>}<div className="duration-picker"><button type="button" onClick={()=>setShowDuration(value=>!value)}><span>المدة المتوقعة</span><b>{arNumber(Number(form.expectedMinutes)||0)} دقيقة</b><i>{showDuration?"⌃":"⌄"}</i></button>{showDuration&&<div className="duration-slider"><input aria-label="المدة المتوقعة بالدقائق" type="range" min="5" max={form.template==="نوم"?"720":"180"} step="5" value={form.expectedMinutes} onChange={event=>update("expectedMinutes",event.target.value)}/><div><span>٥ د</span><strong>{arNumber(Number(form.expectedMinutes))} د</strong><span>{form.template==="نوم"?"١٢ س":"٣ س"}</span></div></div>}</div><label>الهدف <small>اختياري</small><input value={form.goal} onChange={event=>update("goal",event.target.value)} placeholder="لماذا تريد له مكانًا؟"/></label></div>}
  {step===reviewStep&&<div className="wizard-body"><div className="activity-preview"><small>{form.period}</small><h3>{form.name}</h3><p>{form.scheduleValue}</p><div>{isSport&&<span>{arNumber(exercises.length)} تمارين</span>}{form.quantity&&<span>{arNumber(Number(form.quantity))} {suggestedUnit}</span>}<span>{durationLabel(Number(form.expectedMinutes)||0)}</span></div></div>{isSport&&<div className="exercise-preview-list">{exercises.map(item=><p key={item.id}><b>{item.name}</b><span>{arNumber(item.sets)} جولات × {item.measurement==="duration"?`${arNumber(item.durationSeconds??0)} ث`:`${arNumber(item.reps??0)} عدة`}</span></p>)}</div>}<p className="preview-note">سيظهر في خطتك، وفي محطة {form.period} من يومك.</p></div>}
  <div className="wizard-actions">{step>1&&<button className="wizard-back" onClick={()=>setStep(value=>value-1)}>السابق</button>}<button className="primary" disabled={!canContinue} onClick={()=>step<totalSteps?setStep(value=>value+1):submit()}>{step<totalSteps?"التالي":editing?"حفظ التعديلات":"أضف إلى خطتي"}</button></div>
  {editing&&<button className="delete-activity" onClick={()=>{if(window.confirm(`حذف «${editing.name}» من خطتك؟\nسيبقى سجل إنجازاتك السابقة محفوظًا.`)){onDelete(editing.id);close()}}}>حذف النشاط</button>}
 </dialog>
}
type JourneyTask={name:string;meta:string;done:boolean;kind:"goals"|"commitments"|"tasks"|"appointments";progress?:{done:number;target:number;percent:number};activity?:PlannedActivity;task?:TaskItem;appointment?:Appointment};
type JourneyStation={period:string;totalMinutes:number;tasks:JourneyTask[]};
function JourneyFilters({value,onChange}:{value:JourneyFilter;onChange:(value:JourneyFilter)=>void}){
 const filters:{id:JourneyFilter;label:string}[]=[{id:"all",label:"الكل"},{id:"goals",label:"الأهداف"},{id:"commitments",label:"الالتزامات"},{id:"tasks",label:"المهام"},{id:"appointments",label:"المواعيد"}];
 return <div className="journey-filters" role="group" aria-label="تصفية رحلة اليوم">{filters.map(filter=><button key={filter.id} className={value===filter.id?"selected":""} aria-pressed={value===filter.id} onClick={()=>onChange(filter.id)}>{filter.label}</button>)}</div>
}
function DayJourney({journey,selected,current,today,activeDate,calendarMode,remaining,remainingSeconds,prayerStarts,onDateChange,onSelect,onOpen}:{journey:JourneyStation[];selected:number;current:number;today:Date;activeDate:Date;calendarMode:"islamic"|"gregory";remaining:number;remainingSeconds:number;prayerStarts:number[];onDateChange:(date:Date)=>void;onSelect:(index:number)=>void;onOpen:(task:JourneyTask)=>void}){
 const [flipped,setFlipped]=useState(false);
 const [turning,setTurning]=useState<"out"|"in"|null>(null);
 const dateKey=(date:Date)=>`${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
 const todayKey=dateKey(today);
 const weekStart=new Date(today.getFullYear(),today.getMonth(),today.getDate()-((today.getDay()+1)%7));
 const weekDates=Array.from({length:7},(_,index)=>new Date(weekStart.getFullYear(),weekStart.getMonth(),weekStart.getDate()+index));
 const activeKey=dateKey(activeDate),isViewingToday=activeKey===todayKey;
 const dayDistance=Math.round((new Date(activeDate.getFullYear(),activeDate.getMonth(),activeDate.getDate()).getTime()-new Date(today.getFullYear(),today.getMonth(),today.getDate()).getTime())/86400000);
 const effectiveCurrent=isViewingToday?current:dayDistance<0?5:-1;
 const journeyTitle=isViewingToday?"رحلة اليوم":dayDistance===1?"رحلة الغد":`رحلة ${new Intl.DateTimeFormat("ar-SA",{weekday:"long"}).format(activeDate)}`;
 const calendarLocale=calendarMode==="islamic"?"ar-SA-u-ca-islamic-umalqura":"ar-SA-u-ca-gregory";
 const station=journey[selected];
 const stationTime=minuteClockLabel(prayerStarts[selected]);
 const nextStart=selected===4?prayerStarts[0]+1440:prayerStarts[selected+1];
 const windowMinutes=nextStart-prayerStarts[selected];
 const available=selected===effectiveCurrent?remaining:windowMinutes;
 const free=Math.max(0,available-station.totalMinutes);
 const elapsedPercent=selected<effectiveCurrent?100:selected>effectiveCurrent?0:Math.max(0,Math.min(100,((windowMinutes-remaining)/windowMinutes)*100));
 const currentMinute=nextStart-remaining;
 const currentTimeLabel=minuteClockLabel((currentMinute+1440)%1440);
 const endTimeLabel=minuteClockLabel(nextStart%1440);
 const countdownHours=Math.floor(remainingSeconds/3600),countdownMinutes=Math.floor((remainingSeconds%3600)/60),countdownSeconds=remainingSeconds%60;
 const focusTask=station.tasks.find(task=>!task.done)??station.tasks[0]??{name:"لا يوجد نشاط",meta:"لا شيء من هذا النوع في هذه المحطة",done:false,kind:"tasks" as const};
 useEffect(()=>{setFlipped(false);setTurning(null)},[selected]);
 const flip=()=>{if(turning)return;setTurning("out");window.setTimeout(()=>{setFlipped(value=>!value);setTurning("in");window.setTimeout(()=>setTurning(null),260)},210)};
 return <section className="screen day-screen">
  <div className="journey-title"><div><h1>{journeyTitle}</h1><p>{new Intl.DateTimeFormat(calendarLocale,{day:"numeric",month:"long",year:"numeric"}).format(activeDate)}</p></div>{!isViewingToday&&<button onClick={()=>onDateChange(today)}>اليوم</button>}</div>
  <div className="week-strip" aria-label="أيام الأسبوع">{weekDates.map(date=>{const key=dateKey(date),isToday=key===todayKey,isActive=key===activeKey;const dateNumber=new Intl.DateTimeFormat(calendarLocale,{day:"numeric"}).format(date);return <button key={key} className={`${isToday?"today":""} ${isActive?"selected":""}`} onClick={()=>onDateChange(date)}><b>{["ح","ن","ث","ر","خ","ج","س"][date.getDay()]}</b><span>{dateNumber}</span>{isToday&&<i/>}</button>})}</div>
  <div className="journey-strip period-tiles">{journey.map((item,i)=><button key={item.period} className={`${i===selected?"selected":""} ${i<effectiveCurrent?"passed":""} ${i===effectiveCurrent?"live":""}`} onClick={()=>onSelect(i)} aria-label={`${item.period}، يبدأ ${minuteClockLabel(prayerStarts[i])}`}><span className="period-check">{i<effectiveCurrent?"✓":""}</span><b>{item.period}</b><small>{minuteClockLabel(prayerStarts[i])}</small></button>)}</div>
  <div className={`flip-scene ${flipped?"is-flipped":""} ${turning?`turn-${turning}`:""}`}>
   <div className="flip-card">
    {!flipped?<article className={`station-hero flip-face flip-front station-tone-${selected}`} role={station.tasks.length?"button":undefined} tabIndex={station.tasks.length?0:-1} aria-label={station.tasks.length?"إظهار المهمة الحالية":undefined} onClick={()=>station.tasks.length&&flip()} onKeyDown={event=>{if(station.tasks.length&&(event.key==="Enter"||event.key===" ")){event.preventDefault();flip()}}}>
     <div className="hero-top"><div><p>{selected===effectiveCurrent?"محطتك الآن":selected<effectiveCurrent?"محطة مرّت":"محطة أمامك"}</p><h2>{station.period}</h2></div>{selected===effectiveCurrent?<div className="remaining-hero"><span>تنتهي بعد</span><b>{countdownHours>0?<><strong>{arNumber(countdownMinutes)}</strong><small>د</small><strong>{arNumber(countdownHours)}</strong><small>س</small></>:<><strong className="countdown-seconds">{arNumber(countdownSeconds,2)}</strong><small>ث</small><strong>{arNumber(countdownMinutes)}</strong><small>د</small></>}</b></div>:<strong className="hero-status-static">{selected<effectiveCurrent?"انتهت":`تبدأ ${stationTime}`}</strong>}</div>
     <div className={`period-progress ${selected===effectiveCurrent?"is-live":selected<effectiveCurrent?"is-past":"is-next"}`} aria-label={`من ${stationTime} إلى ${endTimeLabel}`}>
      <div className="period-rail"><span className="elapsed-rail" style={{width:`${elapsedPercent}%`}}/>{selected===effectiveCurrent&&<span className="live-time-marker" style={{right:`clamp(8px, ${elapsedPercent}%, calc(100% - 8px))`}}><i/></span>}</div>
      {selected===effectiveCurrent&&<span className="current-time-label" style={{right:`clamp(38px, ${elapsedPercent}%, calc(100% - 38px))`}}>الآن {currentTimeLabel}</span>}
      <div className="period-times"><span>{stationTime}</span><span>{endTimeLabel}</span></div>
     </div>
     <div className="hero-facts"><p><b>{arNumber(station.tasks.length)}</b><span>أنشطة</span></p><p><b>{durationLabel(station.totalMinutes)}</b><span>تحتاج فقط</span></p><p><b>{durationLabel(free)}</b><span>{selected===effectiveCurrent?"يبقى لك":"وقت متسع"}</span></p></div>
     {station.tasks.length?<span className="flip-hint">اضغط لترى مهمتك <b>↻</b></span>:<span className="flip-hint empty">لا شيء في هذه المحطة بعد</span>}
    </article>:<article className={`station-hero flip-face flip-back station-tone-${selected}`} role="button" tabIndex={0} aria-label="العودة إلى ملخص المحطة" onClick={flip} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();flip()}}}>
     <div className="back-kicker"><span>الآن وقت</span><b>↻</b></div>
     <h2>{focusTask.name}</h2>
     <p className="back-duration">{focusTask.meta}</p>
     <p className="back-message">{selected===effectiveCurrent?"أنجزها الآن، والباقي لك.":selected<effectiveCurrent?"كانت هذه مهمتك هنا. انتهى وقتها بهدوء.":"ليست عليك الآن. حين تصلها ستجدها هنا."}</p>
     {selected===effectiveCurrent&&!focusTask.done&&<button className="back-start" onClick={event=>{event.stopPropagation();onOpen(focusTask)}}>{focusTask.appointment||focusTask.task?"فتح التفاصيل":"افتح النشاط"} <span>←</span></button>}
     <span className="flip-hint">اضغط للعودة إلى الوقت <b>↻</b></span>
    </article>}
   </div>
  </div>
  <section className="period-task-section"><h3>ماذا تستطيع أن تنجز في {station.period}؟</h3>{station.tasks.length?<div className="period-task-card">{station.tasks.map(task=><div key={`${task.kind}-${task.name}-${task.meta}`} role="button" tabIndex={0} aria-label={`فتح ${task.name}`} onClick={()=>onOpen(task)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onOpen(task)}}} className={`period-task-row tappable ${task.done?"task-done":""} ${task.appointment?"appointment-row":""}`}><div className="period-task-main"><h4>{task.name}</h4>{task.progress&&<span className="task-unit-progress" aria-label={`${arNumber(task.progress.done)} من ${arNumber(task.progress.target)}`}><i><b style={{width:`${task.progress.percent}%`}}/></i><small>{arNumber(task.progress.done)} من {arNumber(task.progress.target)}</small></span>}</div><b>{task.meta}</b><span className="task-open-arrow" aria-hidden="true">←</span></div>)}</div>:<div className="empty-period"><p>لا شيء هنا من هذا النوع.</p><span>جرّب محطة أخرى أو عد إلى «الكل».</span></div>}</section>
 </section>
}
function Head({kicker,title,text}:{kicker:string;title:string;text:string}){return <div className="screen-head"><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{text}</p></div>}
function SheetHead({kicker,title}:{kicker:string;title:string}){return <div className="sheet-head"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div><button aria-label="إغلاق" onClick={e=>(e.currentTarget.closest("dialog") as HTMLDialogElement).close()}>×</button></div>}
function Now({slot,phase,seconds,pages,elapsed,setPhase,setPages,finish,start,returnToJourney}:any){return <section className="now-view" aria-live="polite">{phase==="idle"&&<><div className="period-block"><p className="eyebrow">{slot.period}</p><p className="until">{slot.next}</p></div><div className="quiet-arc"><span/></div><div className="now-copy"><p className="eyebrow">الآن وقت</p><h1>{slot.activity}</h1><p className="amount">{slot.amount}</p>{slot.reading&&<p className="rate">بمعدل تقريبي <b>٣ دقائق للصفحة</b></p>}<p className="note">{slot.note}</p></div><button className="primary" onClick={start}>{slot.reading?"ابدأ القراءة":"ابدأ"}<span>←</span></button></>}{(phase==="running"||phase==="paused")&&<div className="focus-mode"><p className="eyebrow">قيد التنفيذ</p><h1>{slot.activity}</h1><div className="timer-ring"><div><strong>{fmt(seconds)}</strong><span>باقي من جلستك</span></div></div>{slot.reading&&<div className="page-progress"><strong>{arNumber(pages)} / ٥</strong><span>صفحات</span><button disabled={pages>=5} onClick={()=>setPages((p:number)=>Math.min(5,p+1))}>أنجزت صفحة</button></div>}<div className="session-actions"><button className="soft" onClick={()=>setPhase(phase==="running"?"paused":"running")}>{phase==="running"?"إيقاف مؤقت":"استئناف"}</button><button className="text-button" onClick={finish}>إنهاء النشاط</button></div></div>}{phase==="done"&&<div className="done-state"><span className="done-mark">✓</span><p className="eyebrow">تمت.</p><h1>{elapsed<60?"لحظات":`${arNumber(Math.max(1,Math.round(elapsed/60)))} دقيقة`}</h1><p>الآن وقتك لك.</p><button className="soft" onClick={returnToJourney}>عودة بهدوء</button></div>}</section>}
function Achievements({records,plan,range}:{records:ExecutionRecord[];plan:PlannedActivity[];range:string}){
 const days=range==="week"?7:30,bucketCount=range==="week"?7:4,now=Date.now(),cutoff=now-days*86400000;
 const visible=records.filter(record=>new Date(record.completedAt).getTime()>=cutoff);
 const goals=plan.filter(item=>item.nature==="goal"),commitments=plan.filter(item=>item.nature!=="goal");
 const arabicToNumber=(value:string)=>Number(value.replace(/[٠-٩]/g,digit=>"٠١٢٣٤٥٦٧٨٩".indexOf(digit).toString()).match(/\d+/)?.[0]??1);
 const targetSessions=(activity:PlannedActivity)=>activity.schedule.mode==="daily"?days:activity.schedule.mode==="flexible"?arabicToNumber(activity.schedule.value)*(range==="week"?1:4):Math.max(1,weekDays.filter(day=>activity.schedule.value.includes(day)).length)*(range==="week"?1:4);
 const rows=commitments.map(activity=>{const activityRecords=visible.filter(record=>record.activityId===activity.id||(!record.activityId&&record.activity===activity.name));const planned=targetSessions(activity),actual=activityRecords.filter(record=>record.status!=="missed").length,minutes=activityRecords.reduce((sum,record)=>sum+record.minutes,0),average=actual?minutes/actual:0;return{activity,planned,actual,minutes,average,difference:actual-planned}});
 const plannedMinutes=rows.reduce((sum,row)=>sum+row.planned*row.activity.expectedMinutes,0),actualMinutes=visible.reduce((sum,record)=>sum+record.minutes,0);
 const buckets=Array.from({length:bucketCount},()=>0);visible.forEach(record=>{const age=Math.max(0,now-new Date(record.completedAt).getTime()),index=Math.max(0,Math.min(bucketCount-1,bucketCount-1-Math.floor(age/(days*86400000/bucketCount))));buckets[index]+=record.minutes});
 const cumulative=buckets.reduce<number[]>((values,value,index)=>[...values,value+(values[index-1]??0)],[]),plannedCumulative=Array.from({length:bucketCount},(_,index)=>plannedMinutes*((index+1)/bucketCount));
 const maxValue=Math.max(1,plannedMinutes,actualMinutes),point=(value:number,index:number)=>`${20+(index*(280/Math.max(1,bucketCount-1)))},${145-(value/maxValue)*112}`;
 const actualPoints=cumulative.map(point).join(" "),plannedPoints=plannedCumulative.map(point).join(" ");
 const labels=range==="week"?["س","ح","ن","ث","ر","خ","ج"]:["أسبوع ١","أسبوع ٢","أسبوع ٣","أسبوع ٤"];
 const plannedSessions=rows.reduce((sum,row)=>sum+row.planned,0),actualSessions=rows.reduce((sum,row)=>sum+row.actual,0),progress=plannedSessions?Math.round(actualSessions/plannedSessions*100):0;
 const maxBucket=Math.max(1,...buckets),activeBuckets=buckets.filter(Boolean).length;
 const insightRows=rows.filter(row=>row.actual>0),expectedAverage=insightRows.length?insightRows.reduce((sum,row)=>sum+row.activity.expectedMinutes,0)/insightRows.length:0,actualAverage=actualSessions?actualMinutes/actualSessions:0;
 const status=(difference:number)=>difference>0?{label:"متقدم",key:"positive"}:difference===0?{label:"على المسار",key:"track"}:difference===-1?{label:"قريب",key:"close"}:{label:"يحتاج مكانًا",key:"needs"};
 return <div className="progress-dashboard">
  <section className="achievement-summary"><div><small>التزامك</small><b>{arNumber(progress)}٪</b></div><div><small>أهداف تحركت</small><b>{arNumber(goals.filter(goal=>visible.some(record=>record.activityId===goal.id)).length)}</b></div><p>رقمان مختلفان. لأن المحافظة ليست هي التقدم.</p></section>
  {goals.length>0&&<section className="progress-section"><div className="section-title"><h3>تقدم الأهداف</h3><span>من الحالي إلى المستهدف</span></div><div className="goal-progress-list">{goals.map(goal=>{const definition=goal.goalDefinition;if(!definition)return <article key={goal.id}><div><b>{goal.name}</b><span>حدّث نقطة التقدم من تعديل الهدف.</span></div></article>;const current=definition.currentValue??definition.currentMilestone??0,target=definition.targetValue??definition.targetMilestone??0,percent=definition.kind==="level"?(definition.currentLevel===definition.targetLevel?100:50):(target?Math.min(100,Math.round(current/target*100)):0);return <article key={goal.id}><div><b>{goal.name}</b><span>{definition.kind==="level"?`${definition.currentLevel} ← ${definition.targetLevel}`:`${arNumber(current)} / ${arNumber(target)} ${definition.unit??""}`}</span></div><strong>{arNumber(percent)}٪</strong><i><span style={{width:`${percent}%`}}/></i></article>})}</div></section>}
  <div className="metric-divider"><h3>مدى الالتزام</h3><p>الاستحقاقات المؤداة من المستحقة، لا تقدم الأهداف.</p></div>
  <section className="progress-chart-card"><div className="chart-heading"><div><p>التقدم الزمني</p><h2>{durationLabel(actualMinutes)}</h2></div><div className="chart-legend"><span><i className="actual"/>المنجز</span><span><i className="planned"/>المخطط</span></div></div><svg viewBox="0 0 320 170" role="img" aria-label={`المنجز ${durationLabel(actualMinutes)} من ${durationLabel(plannedMinutes)} مخطط`}><line x1="20" y1="145" x2="300" y2="145" className="chart-axis"/><line x1="20" y1="89" x2="300" y2="89" className="chart-grid"/><line x1="20" y1="33" x2="300" y2="33" className="chart-grid"/><polyline points={plannedPoints} className="planned-line"/><polyline points={actualPoints} className="actual-line"/>{cumulative.map((value,index)=><circle key={index} cx={20+(index*(280/Math.max(1,bucketCount-1)))} cy={145-(value/maxValue)*112} r="3.5" className="actual-point"/>)}</svg><div className={`chart-labels labels-${bucketCount}`}>{labels.map(label=><span key={label}>{label}</span>)}</div><div className="chart-difference"><span>المخطط {durationLabel(plannedMinutes)}</span><b>{actualMinutes>=plannedMinutes?`متقدم بـ ${durationLabel(actualMinutes-plannedMinutes)}`:`متأخر بـ ${durationLabel(plannedMinutes-actualMinutes)}`}</b></div></section>
  <section className="progress-section"><div className="section-title"><h3>الخطة مقابل الفعلي</h3><span>{arNumber(progress)}٪</span></div>{rows.length?<div className="progress-table"><div className="table-head"><span>النشاط</span><span>المخطط</span><span>الفعلي</span><span>الحالة</span></div>{rows.map(row=>{const rowStatus=status(row.difference);return <div className="table-row" key={row.activity.id}><b>{row.activity.name}</b><span>{arNumber(row.planned)}</span><span>{arNumber(row.actual)}</span><em className={`status-${rowStatus.key}`}>{rowStatus.label}</em></div>})}</div>:<div className="empty-inline">أضف نشاطًا إلى خطتك لتظهر المقارنة.</div>}</section>
  <section className="progress-section"><div className="section-title"><h3>توزيع الإنجاز</h3><span>{activeBuckets} من {bucketCount}</span></div><div className={`distribution-chart distribution-${bucketCount}`}>{buckets.map((value,index)=><div key={index}><b style={{height:`${Math.max(value?8:2,(value/maxBucket)*82)}%`}} className={value?"has-value":""}/><span>{labels[index]}</span></div>)}</div></section>
  <section className="progress-section"><div className="section-title"><h3>المتوقع مقابل الوقت الحقيقي</h3><span>متوسط الجلسة</span></div>{insightRows.length?<div className="time-table">{insightRows.map(row=><div key={row.activity.id}><b>{row.activity.name}</b><span>توقعت {durationLabel(row.activity.expectedMinutes)}</span><span>فعليًا {durationLabel(Math.round(row.average))}</span><em>{row.average<=row.activity.expectedMinutes?`أقل بـ ${durationLabel(Math.round(row.activity.expectedMinutes-row.average))}`:`أكثر بـ ${durationLabel(Math.round(row.average-row.activity.expectedMinutes))}`}</em></div>)}</div>:<div className="empty-inline">ينكشف الفرق بعد أول جلسة حقيقية.</div>}</section>
  <section className="insights"><p>ما أصبح واضحًا</p>{visible.length?<><h3>{progress>=100?"أنت متقدم على خطتك.":progress>=70?"أنت قريب من خطتك.":"التأخر في عدد الجلسات، لا في حجمها."}</h3><span>{activeBuckets<=Math.ceil(bucketCount/3)?"إنجازك متجمع في أيام قليلة؛ توزيعه سيخفف ثقل الخطة.":"إنجازك موزع جيدًا عبر الفترة."}</span>{expectedAverage>0&&<span>{actualAverage<expectedAverage?`جلساتك أقصر من توقعك بنحو ${durationLabel(Math.round(expectedAverage-actualAverage))}.`:`جلساتك أطول من المتوقع بنحو ${durationLabel(Math.round(actualAverage-expectedAverage))}.`}</span>}</>:<><h3>لا قراءة بلا فعل.</h3><span>أكمل أول نشاط، وسيبدأ الرسم من بياناتك أنت.</span></>}</section>
 </div>
}
