"use client";
import { useEffect, useMemo, useState } from "react";
import { activities, settings, templates, type Tab } from "./data";
import { clockLabel, durationLabel, fitsWindow, minuteClockLabel, resolveTimeWindow } from "./time-engine";
import { deletePlan, readExecutionLog, readPlan, saveExecution, savePlan, updatePlan, type ExecutionRecord, type PlannedActivity, type WorkoutExercise } from "./local-store";
import WorkoutRunner from "./WorkoutRunner";
import { calisthenicsCatalog } from "./workout-data";

type Phase="idle"|"running"|"paused"|"done";
const slots=[
 {time:"—",period:"الصباح",activity:"القراءة",amount:"٥ صفحات",minutes:15,note:"أنجز… ولو لم تستمتع يا هذا.",reading:true,next:"الظهر"},
 {time:"١٣:٠٠",period:"الظهر",activity:"المشي",amount:"٢٠ دقيقة",minutes:20,note:"قم وامشِ. التفكير في المشي لا يُحسب مشيًا.",next:"العصر بعد ٣:٣٠"},
 {time:"١٦:٣٠",period:"العصر",activity:"الرياضة",amount:"٣٠ دقيقة فقط",minutes:30,note:"أنجزها الآن، واستمتع بباقي وقتك.",next:"المغرب بعد ٢:٢٥"},
 {time:"—",period:"المغرب",activity:"المهارة",amount:"٢٠ دقيقة",minutes:20,note:"جلسة واحدة تكفي. لا نؤلف ملحمة.",next:"الليل"},
 {time:"—",period:"الليل",activity:"النوم",amount:"٧ ساعات",minutes:420,note:"يكفي لهذا اليوم. أغلقه بهدوء.",next:"الصباح"},
];
const nav:{id:Tab;label:string;icon:string}[]=[{id:"plan",label:"التخطيط",icon:"⌁"},{id:"day",label:"التنفيذ",icon:"●"},{id:"done",label:"الإنجاز",icon:"⌇"}];
const arNumber=(value:number,pad=1)=>value.toLocaleString("ar-SA",{minimumIntegerDigits:Math.max(1,pad),useGrouping:false});
const fmt=(s:number)=>`${arNumber(Math.floor(s/60),2)}:${arNumber(s%60,2)}`;

export default function Home(){
 const [tab,setTab]=useState<Tab>("day"),[drawerOpen,setDrawerOpen]=useState(false),[calendarMode,setCalendarMode]=useState<"islamic"|"gregory">("gregory"),[activeWorkout,setActiveWorkout]=useState<PlannedActivity|null>(null),[editingActivity,setEditingActivity]=useState<PlannedActivity|null>(null),[previewIndex,setPreviewIndex]=useState(2),[dayPeriod,setDayPeriod]=useState<number|null>(null),[live,setLive]=useState(true),[clock,setClock]=useState<Date|null>(null),[phase,setPhase]=useState<Phase>("idle"),[pages,setPages]=useState(0),[prayer,setPrayer]=useState(""),[range,setRange]=useState("week"),[plan,setPlan]=useState<PlannedActivity[]>([]),[executionRecords,setExecutionRecords]=useState<ExecutionRecord[]>([]),[savedCount,setSavedCount]=useState(0); const fallbackClock=new Date(2020,0,1,16,30); const windowNow=resolveTimeWindow(clock??fallbackClock); const prayerStarts=[windowNow.times.fajr,windowNow.times.dhuhr,windowNow.times.asr,windowNow.times.maghrib,windowNow.times.isha]; const prayerClocks=prayerStarts.map(minuteClockLabel); const slotIndex=live&&clock?windowNow.index:previewIndex; const baseSlot=slots[slotIndex]; const isShort=live&&!!clock&&!fitsWindow(baseSlot.minutes,windowNow.remainingMinutes); const suggestedMinutes=isShort?Math.max(1,windowNow.remainingMinutes):baseSlot.minutes; const nextPeriod=windowNow.nextName==="الفجر"?"الصباح":windowNow.nextName; const slot={...baseSlot,time:prayerClocks[slotIndex],minutes:suggestedMinutes,amount:isShort?`نسخة مختصرة · ${durationLabel(suggestedMinutes)}`:baseSlot.amount,note:isShort?"هذا ما يتسع له الوقت الآن. يكفي.":baseSlot.note,next:live&&clock?`${nextPeriod} بعد ${durationLabel(windowNow.remainingMinutes)}`:`${["الظهر","العصر","المغرب","الليل","الصباح"][slotIndex]} عند ${prayerClocks[(slotIndex+1)%5]}`}; const [seconds,setSeconds]=useState(baseSlot.minutes*60); const selectedDay=dayPeriod??slotIndex;
 const riyadhDay=(value:Date|string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value));
 const calendarLocale=calendarMode==="islamic"?"ar-SA-u-ca-islamic-umalqura":"ar-SA-u-ca-gregory";
 const plannedJourney=useMemo(()=>slots.map(item=>{const periodActivities=plan.filter(activity=>activity.period===item.period);return{period:item.period,totalMinutes:periodActivities.reduce((sum,activity)=>sum+activity.expectedMinutes,0),tasks:periodActivities.map(activity=>({name:activity.name,meta:[activity.exercises?.length?`${arNumber(activity.exercises.length)} تمارين`:activity.quantity&&activity.unit?`${arNumber(activity.quantity)} ${activity.unit}`:"",activity.expectedMinutes?durationLabel(activity.expectedMinutes):""].filter(Boolean).join(" · "),done:executionRecords.some(record=>record.activityId===activity.id&&riyadhDay(record.completedAt)===riyadhDay(clock??fallbackClock)),activity}))}}),[plan,executionRecords,clock]);
 useEffect(()=>{const records=readExecutionLog();setClock(new Date());setPlan(readPlan());setExecutionRecords(records);setSavedCount(records.length);setCalendarMode(localStorage.getItem("sair.calendar.v1")==="islamic"?"islamic":"gregory");const t=window.setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(t)},[]);
 const changeCalendar=(mode:"islamic"|"gregory")=>{setCalendarMode(mode);localStorage.setItem("sair.calendar.v1",mode);setDrawerOpen(false)};
 useEffect(()=>{if(phase!=="running")return;const t=window.setInterval(()=>setSeconds(v=>v>0?v-1:0),1000);return()=>clearInterval(t)},[phase]);
 useEffect(()=>{if(seconds===0&&phase==="running")setPhase("done")},[seconds,phase]);
 const elapsed=useMemo(()=>Math.max(0,slot.minutes*60-seconds),[seconds,slot.minutes]);
 const reset=(i=slotIndex,isLive=false)=>{setPreviewIndex(i);setLive(isLive);setPhase("idle");setSeconds(slots[i].minutes*60);setPages(0)};
 const recordExecution=(record:ExecutionRecord)=>{setSavedCount(saveExecution(record));setExecutionRecords(readExecutionLog())};
 const finish=()=>{const minutes=Math.max(1,Math.round(elapsed/60));recordExecution({activity:slot.activity,minutes,quantity:slot.reading?pages:undefined,quantityUnit:slot.reading?"صفحة":undefined,completedAt:new Date().toISOString()});setPhase("done")};
 const startCurrent=()=>{setSeconds(slot.minutes*60);setPages(0);setPhase("running")};
 const startTask=(activity?:PlannedActivity)=>{if(activity?.template==="رياضة"&&activity.exercises?.length){setActiveWorkout(activity);return}startCurrent()};
 const openActivity=(activity:PlannedActivity|null)=>{setEditingActivity(activity);window.setTimeout(()=>$("add-sheet")?.showModal(),0)};
 return <main className={`app-shell tone-${slotIndex}`} dir="rtl">
  <header className="topbar"><button className="menu-trigger" aria-label="فتح قائمة أنت" aria-expanded={drawerOpen} onClick={()=>setDrawerOpen(true)}><i/><i/><i/></button>{tab==="day"&&phase==="idle"&&!activeWorkout?<button className="time-trigger" onClick={()=>$("time-sheet")?.showModal()}><i/>{live?(clock?clockLabel(clock):"الوقت الفعلي"):slot.time}<span>⌄</span></button>:<p className="top-date">{clock?new Intl.DateTimeFormat(calendarLocale,{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(clock):"اليوم في الرياض"}</p>}</header>
  {tab==="day"&&activeWorkout&&<WorkoutRunner activity={activeWorkout} onExit={()=>setActiveWorkout(null)} onFinish={(minutes,repetitions)=>{recordExecution({activityId:activeWorkout.id,activity:activeWorkout.name,minutes,quantity:repetitions,quantityUnit:"عدة",completedAt:new Date().toISOString()});setActiveWorkout(null)}}/>}
  {tab==="day"&&!activeWorkout&&phase!=="idle"&&<Now slot={slot} phase={phase} seconds={seconds} pages={pages} elapsed={elapsed} fits={fitsWindow(slot.minutes,windowNow.remainingMinutes)} live={live} setPhase={setPhase} setPages={setPages} finish={finish} start={startCurrent}/>} 
  {tab==="day"&&!activeWorkout&&phase==="idle"&&<DayJourney journey={plannedJourney} selected={selectedDay} current={slotIndex} today={clock??fallbackClock} calendarMode={calendarMode} remaining={windowNow.remainingMinutes} remainingSeconds={Math.max(0,windowNow.remainingMinutes*60-(clock?.getSeconds()??0))} prayerStarts={prayerStarts} onSelect={setDayPeriod} onStart={startTask}/>} 
  {tab==="plan"&&<section className="screen"><Head kicker="ما اخترته لحياتك" title="الخطة" text="ليست قائمة واجبات. هذه الأشياء التي قررت أن تجد لها مكانًا."/><button className="primary add" onClick={()=>openActivity(null)}>+ إضافة إلى خطتي</button>{plan.length?<div className="activity-list">{plan.map(a=><button key={a.id} onClick={()=>openActivity(a)}><span className="activity-icon">{a.template[0]}</span><div><h3>{a.name}</h3><p>{a.period} · {a.schedule.value}</p></div><span>‹</span></button>)}</div>:<div className="empty-plan"><span>○</span><h3>خطتك خفيفة الآن.</h3><p>أضف أول شيء تريد أن تجعل له مكانًا في حياتك.</p></div>}<p className="principle">سائر لا يدير العادات؛ بل الأشياء التي تريد أن تجعل لها مكانًا في حياتك.</p></section>}
  {tab==="done"&&<section className="screen achievement-screen"><Head kicker="حقيقة وقتك" title="الإنجاز" text="اقرأ تقدمك وتأخرك كما حدثا فعلًا."/><div className="segmented"><button className={range==="week"?"on":""} onClick={()=>setRange("week")}>هذا الأسبوع</button><button className={range==="month"?"on":""} onClick={()=>setRange("month")}>هذا الشهر</button></div><Achievements records={executionRecords} plan={plan} range={range}/></section>}
  <nav className="bottom-nav bottom-nav-three">{nav.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>{setTab(n.id);if(n.id!=="day"){setPhase("idle");setActiveWorkout(null)}}}><span>{n.icon}</span>{n.label}</button>)}</nav>
  <div className={`drawer-backdrop ${drawerOpen?"open":""}`} onClick={()=>setDrawerOpen(false)} aria-hidden={!drawerOpen}/>
  <aside className={`you-drawer ${drawerOpen?"open":""}`} aria-hidden={!drawerOpen}><div className="drawer-head"><div><span className="brand-mark">س</span><div><b>سائر</b><small>كما تحب أن تُعامَل</small></div></div><button aria-label="إغلاق" onClick={()=>setDrawerOpen(false)}>×</button></div><section className="calendar-setting"><div><h3>التاريخ</h3><p>كيف تريد أن ترى أيامك؟</p></div><div className="calendar-switch"><button className={calendarMode==="islamic"?"selected":""} onClick={()=>changeCalendar("islamic")}>هجري</button><button className={calendarMode==="gregory"?"selected":""} onClick={()=>changeCalendar("gregory")}>ميلادي</button></div></section><div className="settings-list">{settings.map(x=><button key={x.title}><div><h3>{x.title}</h3><p>{x.note}</p></div><span>‹</span></button>)}</div><p className="version">سائر · نموذج أولي ٠.١</p></aside>
  <TimeSheet live={live} clock={clock} slotIndex={slotIndex} prayerClocks={prayerClocks} reset={reset} setClock={setClock}/>
  <AddActivitySheet editing={editingActivity} onSave={activity=>setPlan(editingActivity?updatePlan(activity):savePlan(activity))} onDelete={id=>{setPlan(deletePlan(id));setEditingActivity(null)}}/>
  <dialog id="sport-sheet" className="sheet detail"><SheetHead kicker="رياضة · العصر" title="تمارين مقاومة"/><div className="detail-meta"><span>٤ جلسات أسبوعيًا</span><span>٣٥ دقيقة</span><span>وقت + جلسات + تكرارات</span></div><div className="exercise-list">{activities[1].items?.map(x=><div key={x.name}><b>{x.name}</b><span>{arNumber(x.sets)} جلسات × {arNumber(x.reps)} تكرارًا</span></div>)}</div><div className="result"><small>نتيجة جلسة سابقة</small><b>٣٢ دقيقة</b><span>١٠ جلسات · ١١٢ تكرارًا</span></div></dialog>
  <dialog id="prayer-sheet" className="sheet"><SheetHead kicker="تسجيل سريع" title="الصلاة مع الجماعة"/><p className="sheet-copy">كيف أدركت الصلاة؟ ضغطة واحدة تكفي.</p><div className="prayer-options">{activities[3].completionStates?.map(s=><button className={prayer===s?"selected":""} key={s} onClick={()=>setPrayer(s)}>{s}<span>{prayer===s?"✓":""}</span></button>)}</div>{prayer&&<p className="recorded">سُجلت: {prayer}</p>}</dialog>
 </main>
}

const $=(id:string)=>document.getElementById(id) as HTMLDialogElement|null;
function TimeSheet({live,clock,slotIndex,prayerClocks,reset,setClock}:{live:boolean;clock:Date|null;slotIndex:number;prayerClocks:string[];reset:(index:number,isLive?:boolean)=>void;setClock:(date:Date)=>void}){
 return <dialog id="time-sheet" className="sheet"><SheetHead kicker="أداة النموذج" title="اختر محطة زمنية"/><div className="time-options"><button className={live?"selected live-time":"live-time"} onClick={()=>{const now=new Date();reset(resolveTimeWindow(now).index,true);setClock(now);$("time-sheet")?.close()}}><span>الوقت الفعلي · الرياض</span><b>{clock?clockLabel(clock):"—"}</b></button>{slots.map((item,index)=><button key={item.period} className={!live&&index===slotIndex?"selected":""} onClick={()=>{reset(index);$("time-sheet")?.close()}}><span>{item.period}</span><b>{prayerClocks[index]}</b></button>)}</div><p className="prototype-note">المحطات مرتبطة بحساب مواقيت الصلاة في الرياض، وتتجدد يوميًا دون اتصال خارجي.</p></dialog>
}
const weekDays=["السبت","الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة"];
const initialActivity={template:"",name:"",period:"العصر",scheduleMode:"fixed" as "daily"|"fixed"|"flexible",scheduleValue:"",days:[] as string[],goal:"",quantity:"",unit:"",expectedMinutes:"20",startTime:"",endTime:""};
function AddActivitySheet({editing,onSave,onDelete}:{editing:PlannedActivity|null;onSave:(activity:PlannedActivity)=>void;onDelete:(id:string)=>void}){
 const [step,setStep]=useState(1),[form,setForm]=useState(initialActivity),[showDuration,setShowDuration]=useState(false),[exercises,setExercises]=useState<WorkoutExercise[]>([]);
 useEffect(()=>{if(!editing){setForm(initialActivity);setExercises([]);setStep(1);return}const days=editing.schedule.mode==="daily"?weekDays:weekDays.filter(day=>editing.schedule.value.includes(day));setForm({template:editing.template,name:editing.name,period:editing.period,scheduleMode:editing.schedule.mode,scheduleValue:editing.schedule.value,days,goal:editing.goal,quantity:editing.quantity?.toString()??"",unit:editing.unit??"",expectedMinutes:editing.expectedMinutes.toString(),startTime:editing.startTime??"",endTime:editing.endTime??""});setExercises(editing.exercises?.map(item=>({...item}))??[]);setStep(1)},[editing]);
 const update=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
 const templateMeasurements:Record<string,string[]>={"رياضة":["الوقت","الجلسات","التكرارات"],"قراءة":["الوقت","الصفحات"],"نوم":["فترة بين وقتين"],"صيام":["فترة بين وقتين"],"عادة":["تم / لم يتم"],"مهارة":["الوقت","الجلسات"],"شيء آخر":["الوقت"]};
 const suggestedUnit=form.template==="قراءة"?"صفحات":form.template==="رياضة"?"تكرارات":form.template==="مهارة"?"جلسات":form.unit;
 const daysLabel=(days:string[])=>days.length===7?"جميع الأيام":days.join("، ");
 const toggleDay=(day:string)=>setForm(current=>{const days=current.days.includes(day)?current.days.filter(item=>item!==day):[...current.days,day];return{...current,days,scheduleMode:days.length===7?"daily":"fixed",scheduleValue:daysLabel(days)}});
 const toggleAllDays=()=>setForm(current=>{const days=current.days.length===7?[]:weekDays;return{...current,days,scheduleMode:days.length===7?"daily":"fixed",scheduleValue:daysLabel(days)}});
 const close=()=>{$("add-sheet")?.close();setStep(1);setShowDuration(false);if(!editing){setExercises([]);setForm(initialActivity)}};
 const isSport=form.template==="رياضة",totalSteps=isSport?5:4,measureStep=isSport?4:3,reviewStep=isSport?5:4;
 const toggleExercise=(exercise:WorkoutExercise)=>setExercises(current=>current.some(item=>item.id===exercise.id)?current.filter(item=>item.id!==exercise.id):[...current,{...exercise}]);
 const updateExercise=(id:string,key:keyof WorkoutExercise,value:number)=>setExercises(current=>current.map(item=>item.id===id?{...item,[key]:value}:item));
 const submit=()=>{onSave({id:editing?.id??`activity-${Date.now()}`,name:form.name.trim(),template:form.template,period:form.period,goal:form.goal.trim(),expectedMinutes:Math.max(0,Number(form.expectedMinutes)||0),schedule:{mode:form.scheduleMode,value:form.scheduleValue||"غير محدد"},quantity:form.quantity?Number(form.quantity):undefined,unit:suggestedUnit||undefined,measurements:templateMeasurements[form.template]??["الوقت"],startTime:form.startTime||undefined,endTime:form.endTime||undefined,exercises:isSport?exercises:undefined});close()};
 const canContinue=step===1?Boolean(form.template&&form.name.trim()):isSport&&step===3?exercises.length>0:true;
 const titles=isSport?["ماذا تريد أن تجعل له مكانًا؟","متى يجد مكانه؟","اختر تمارين الجلسة","ما المقدار الكافي؟","راجع نشاطك"]:["ماذا تريد أن تجعل له مكانًا؟","متى يجد مكانه؟","ما المقدار الكافي؟","راجع نشاطك"];
 return <dialog id="add-sheet" className="sheet activity-wizard"><div className="wizard-head"><div><p>{editing?"تعديل النشاط":"نشاط جديد"} · {arNumber(step)} من {arNumber(totalSteps)}</p><h2>{titles[step-1]}</h2></div><button aria-label="إغلاق" onClick={close}>×</button></div><div className="wizard-progress"><span style={{width:`${step*(100/totalSteps)}%`}}/></div>
  {step===1&&<div className="wizard-body"><label>اسم النشاط<input value={form.name} onChange={event=>update("name",event.target.value)} placeholder="مثال: تمارين المقاومة"/></label><div className="field-label">اختر أقرب قالب</div><div className="templates">{templates.map(template=><button type="button" key={template} className={form.template===template?"selected":""} onClick={()=>{update("template",template);if(!form.name)update("name",template)}}><span>{template}</span><i>{form.template===template?"✓":"+"}</i></button>)}</div></div>}
  {step===2&&<div className="wizard-body"><div className="field-label">في أي فترة؟</div><div className="choice-row">{["الصباح","الظهر","العصر","المغرب","الليل"].map(period=><button className={form.period===period?"selected":""} key={period} onClick={()=>update("period",period)}>{period}</button>)}</div><div className="field-label repeat-title"><span>كيف يتكرر؟</span><button className={form.days.length===7?"selected":""} onClick={toggleAllDays}><b>∞</b> جميع الأيام</button></div><div className="week-days">{weekDays.map(day=><button className={form.days.includes(day)?"selected":""} key={day} onClick={()=>toggleDay(day)}><span>{day}</span></button>)}</div>{form.days.length>0&&<p className="days-summary">{daysLabel(form.days)}</p>}</div>}
  {isSport&&step===3&&<div className="wizard-body exercise-builder"><p className="builder-note">اختر ما ستؤديه فعلًا. يمكنك ضبط كل تمرين بعد إضافته.</p>{["دفع","سحب","أرجل","جذع"].map(category=><section key={category}><h3>{category}</h3><div className="exercise-choices">{calisthenicsCatalog.filter(item=>item.category===category).map(item=><button key={item.id} className={exercises.some(x=>x.id===item.id)?"selected":""} onClick={()=>toggleExercise(item)}><span>{item.name}</span><b>{exercises.some(x=>x.id===item.id)?"✓":"+"}</b></button>)}</div></section>)}{exercises.length>0&&<div className="selected-exercises">{exercises.map(item=><article key={item.id}><div><h4>{item.name}</h4><span>{item.measurement==="duration"?"تمرين زمني":"تمرين بالعدات"}</span></div><label>الجولات<input type="number" min="1" max="10" value={item.sets} onChange={event=>updateExercise(item.id,"sets",Number(event.target.value))}/></label>{item.measurement==="duration"?<label>الثواني<input type="number" min="5" value={item.durationSeconds} onChange={event=>updateExercise(item.id,"durationSeconds",Number(event.target.value))}/></label>:<label>العدات<input type="number" min="1" value={item.reps} onChange={event=>updateExercise(item.id,"reps",Number(event.target.value))}/></label>}<label>الراحة<input type="number" min="0" step="15" value={item.restSeconds} onChange={event=>updateExercise(item.id,"restSeconds",Number(event.target.value))}/><small>ث</small></label></article>)}</div>}</div>}
  {step===measureStep&&<div className="wizard-body">{["نوم","صيام"].includes(form.template)?<div className="time-range"><label>يبدأ<input type="time" value={form.startTime} onChange={event=>update("startTime",event.target.value)}/></label><label>ينتهي<input type="time" value={form.endTime} onChange={event=>update("endTime",event.target.value)}/></label></div>:<><div className="measure-note">سيُقاس بـ: {(templateMeasurements[form.template]??["الوقت"]).join(" + ")}</div>{!isSport&&<div className="split-fields"><label>الوحدة<select value={suggestedUnit} onChange={event=>update("unit",event.target.value)}><option value="">اختر الوحدة</option>{["صفحة","عدة","مرة","تكرار","جلسة","دقيقة","ساعة","متر","كيلومتر","خطوة","كوب","عنصر"].map(unit=><option key={unit} value={unit}>{unit}</option>)}</select></label><label>الكمية<input inputMode="decimal" value={form.quantity} onChange={event=>update("quantity",event.target.value)} placeholder="٥"/></label></div>}</>}<div className="duration-picker"><button type="button" onClick={()=>setShowDuration(value=>!value)}><span>المدة المتوقعة</span><b>{arNumber(Number(form.expectedMinutes)||0)} دقيقة</b><i>{showDuration?"⌃":"⌄"}</i></button>{showDuration&&<div className="duration-slider"><input aria-label="المدة المتوقعة بالدقائق" type="range" min="5" max={form.template==="نوم"?"720":"180"} step="5" value={form.expectedMinutes} onChange={event=>update("expectedMinutes",event.target.value)}/><div><span>٥ د</span><strong>{arNumber(Number(form.expectedMinutes))} د</strong><span>{form.template==="نوم"?"١٢ س":"٣ س"}</span></div></div>}</div><label>الهدف <small>اختياري</small><input value={form.goal} onChange={event=>update("goal",event.target.value)} placeholder="لماذا تريد له مكانًا؟"/></label></div>}
  {step===reviewStep&&<div className="wizard-body"><div className="activity-preview"><small>{form.period}</small><h3>{form.name}</h3><p>{form.scheduleValue}</p><div>{isSport&&<span>{arNumber(exercises.length)} تمارين</span>}{form.quantity&&<span>{arNumber(Number(form.quantity))} {suggestedUnit}</span>}<span>{durationLabel(Number(form.expectedMinutes)||0)}</span></div></div>{isSport&&<div className="exercise-preview-list">{exercises.map(item=><p key={item.id}><b>{item.name}</b><span>{arNumber(item.sets)} جولات × {item.measurement==="duration"?`${arNumber(item.durationSeconds??0)} ث`:`${arNumber(item.reps??0)} عدة`}</span></p>)}</div>}<p className="preview-note">سيظهر في خطتك، وفي محطة {form.period} من يومك.</p></div>}
  <div className="wizard-actions">{step>1&&<button className="wizard-back" onClick={()=>setStep(value=>value-1)}>السابق</button>}<button className="primary" disabled={!canContinue} onClick={()=>step<totalSteps?setStep(value=>value+1):submit()}>{step<totalSteps?"التالي":editing?"حفظ التعديلات":"أضف إلى خطتي"}</button></div>
  {editing&&<button className="delete-activity" onClick={()=>{if(window.confirm(`حذف «${editing.name}» من خطتك؟\nسيبقى سجل إنجازاتك السابقة محفوظًا.`)){onDelete(editing.id);close()}}}>حذف النشاط</button>}
 </dialog>
}
type JourneyTask={name:string;meta:string;done:boolean;activity?:PlannedActivity};
type JourneyStation={period:string;totalMinutes:number;tasks:JourneyTask[]};
function DayJourney({journey,selected,current,today,calendarMode,remaining,remainingSeconds,prayerStarts,onSelect,onStart}:{journey:JourneyStation[];selected:number;current:number;today:Date;calendarMode:"islamic"|"gregory";remaining:number;remainingSeconds:number;prayerStarts:number[];onSelect:(index:number)=>void;onStart:(activity?:PlannedActivity)=>void}){
 const [flipped,setFlipped]=useState(false);
 const [turning,setTurning]=useState<"out"|"in"|null>(null);
 const [selectedDateKey,setSelectedDateKey]=useState("");
 const dateKey=(date:Date)=>`${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
 const todayKey=dateKey(today);
 const weekStart=new Date(today.getFullYear(),today.getMonth(),today.getDate()-((today.getDay()+1)%7));
 const weekDates=Array.from({length:7},(_,index)=>new Date(weekStart.getFullYear(),weekStart.getMonth(),weekStart.getDate()+index));
 const activeDate=weekDates.find(date=>dateKey(date)===(selectedDateKey||todayKey))??today;
 const activeKey=dateKey(activeDate),isViewingToday=activeKey===todayKey;
 const dayDistance=Math.round((new Date(activeDate.getFullYear(),activeDate.getMonth(),activeDate.getDate()).getTime()-new Date(today.getFullYear(),today.getMonth(),today.getDate()).getTime())/86400000);
 const effectiveCurrent=isViewingToday?current:dayDistance<0?5:-1;
 const journeyTitle=isViewingToday?"رحلة اليوم":dayDistance===1?"رحلة الغد":`رحلة ${new Intl.DateTimeFormat("ar-SA",{weekday:"long"}).format(activeDate)}`;
 const calendarLocale=calendarMode==="islamic"?"ar-SA-u-ca-islamic-umalqura":"ar-SA-u-ca-gregory";
 const station=journey[selected];
 const stationTime=minuteClockLabel(prayerStarts[selected]);
 const nextStart=selected===4?prayerStarts[0]+1440:prayerStarts[selected+1];
 const windowMinutes=nextStart-prayerStarts[selected];
 const available=selected===effectiveCurrent?remaining:windowMinutes;
 const free=Math.max(0,available-station.totalMinutes);
 const elapsedPercent=selected<effectiveCurrent?100:selected>effectiveCurrent?0:Math.max(0,Math.min(100,((windowMinutes-remaining)/windowMinutes)*100));
 const currentMinute=nextStart-remaining;
 const currentTimeLabel=minuteClockLabel((currentMinute+1440)%1440);
 const endTimeLabel=minuteClockLabel(nextStart%1440);
 const countdownHours=Math.floor(remainingSeconds/3600),countdownMinutes=Math.floor((remainingSeconds%3600)/60),countdownSeconds=remainingSeconds%60;
 const focusTask=station.tasks.find(task=>!task.done)??station.tasks[0]??{name:"لا يوجد نشاط",meta:"أضف نشاطًا لهذه الفترة من الخطة",done:false};
 useEffect(()=>{setFlipped(false);setTurning(null)},[selected]);
 const flip=()=>{if(turning)return;setTurning("out");window.setTimeout(()=>{setFlipped(value=>!value);setTurning("in");window.setTimeout(()=>setTurning(null),260)},210)};
 return <section className="screen day-screen">
  <div className="journey-title"><div><h1>{journeyTitle}</h1><p>{new Intl.DateTimeFormat(calendarLocale,{day:"numeric",month:"long",year:"numeric"}).format(activeDate)}</p></div>{!isViewingToday&&<button onClick={()=>{setSelectedDateKey(todayKey);onSelect(current)}}>اليوم</button>}</div>
  <div className="week-strip" aria-label="أيام الأسبوع">{weekDates.map(date=>{const key=dateKey(date),isToday=key===todayKey,isActive=key===activeKey;const dateNumber=new Intl.DateTimeFormat(calendarLocale,{day:"numeric"}).format(date);return <button key={key} className={`${isToday?"today":""} ${isActive?"selected":""}`} onClick={()=>{setSelectedDateKey(key);onSelect(key===todayKey?current:0)}}><b>{["ح","ن","ث","ر","خ","ج","س"][date.getDay()]}</b><span>{dateNumber}</span>{isToday&&<i/>}</button>})}</div>
  <div className="journey-strip period-tiles">{journey.map((item,i)=><button key={item.period} className={`${i===selected?"selected":""} ${i<effectiveCurrent?"passed":""} ${i===effectiveCurrent?"live":""}`} onClick={()=>onSelect(i)} aria-label={`${item.period}، يبدأ ${minuteClockLabel(prayerStarts[i])}`}><span className="period-check">{i<effectiveCurrent?"✓":""}</span><b>{item.period}</b><small>{minuteClockLabel(prayerStarts[i])}</small></button>)}</div>
  <div className={`flip-scene ${flipped?"is-flipped":""} ${turning?`turn-${turning}`:""}`}>
   <div className="flip-card">
    {!flipped?<article className={`station-hero flip-face flip-front station-tone-${selected}`} role={station.tasks.length?"button":undefined} tabIndex={station.tasks.length?0:-1} aria-label={station.tasks.length?"إظهار المهمة الحالية":undefined} onClick={()=>station.tasks.length&&flip()} onKeyDown={event=>{if(station.tasks.length&&(event.key==="Enter"||event.key===" ")){event.preventDefault();flip()}}}>
     <div className="hero-top"><div><p>{selected===effectiveCurrent?"محطتك الآن":selected<effectiveCurrent?"محطة مرّت":"محطة أمامك"}</p><h2>{station.period}</h2></div>{selected===effectiveCurrent?<div className="remaining-hero"><span>تنتهي بعد</span><b>{countdownHours>0?<><strong>{arNumber(countdownMinutes)}</strong><small>د</small><strong>{arNumber(countdownHours)}</strong><small>س</small></>:<><strong className="countdown-seconds">{arNumber(countdownSeconds,2)}</strong><small>ث</small><strong>{arNumber(countdownMinutes)}</strong><small>د</small></>}</b></div>:<strong className="hero-status-static">{selected<effectiveCurrent?"انتهت":`تبدأ ${stationTime}`}</strong>}</div>
     <div className={`period-progress ${selected===effectiveCurrent?"is-live":selected<effectiveCurrent?"is-past":"is-next"}`} aria-label={`من ${stationTime} إلى ${endTimeLabel}`}>
      <div className="period-rail"><span className="elapsed-rail" style={{width:`${elapsedPercent}%`}}/>{selected===effectiveCurrent&&<span className="live-time-marker" style={{right:`clamp(8px, ${elapsedPercent}%, calc(100% - 8px))`}}><i/></span>}</div>
      {selected===effectiveCurrent&&<span className="current-time-label" style={{right:`clamp(38px, ${elapsedPercent}%, calc(100% - 38px))`}}>الآن {currentTimeLabel}</span>}
      <div className="period-times"><span>{stationTime}</span><span>{endTimeLabel}</span></div>
     </div>
     <div className="hero-facts"><p><b>{arNumber(station.tasks.length)}</b><span>أنشطة</span></p><p><b>{durationLabel(station.totalMinutes)}</b><span>تحتاج فقط</span></p><p><b>{durationLabel(free)}</b><span>{selected===effectiveCurrent?"يبقى لك":"وقت متسع"}</span></p></div>
     {station.tasks.length?<span className="flip-hint">اضغط لترى مهمتك <b>↻</b></span>:<span className="flip-hint empty">لا شيء في هذه المحطة بعد</span>}
    </article>:<article className={`station-hero flip-face flip-back station-tone-${selected}`} role="button" tabIndex={0} aria-label="العودة إلى ملخص المحطة" onClick={flip} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();flip()}}}>
     <div className="back-kicker"><span>الآن وقت</span><b>↻</b></div>
     <h2>{focusTask.name}</h2>
     <p className="back-duration">{focusTask.meta}</p>
     <p className="back-message">{selected===effectiveCurrent?"أنجزها الآن، والباقي لك.":selected<effectiveCurrent?"كانت هذه مهمتك هنا. انتهى وقتها بهدوء.":"ليست عليك الآن. حين تصلها ستجدها هنا."}</p>
     {selected===effectiveCurrent&&!focusTask.done&&<button className="back-start" onClick={event=>{event.stopPropagation();onStart(focusTask.activity)}}>ابدأ الآن <span>←</span></button>}
     <span className="flip-hint">اضغط للعودة إلى الوقت <b>↻</b></span>
    </article>}
   </div>
  </div>
  <section className="period-task-section"><h3>ماذا تستطيع أن تنجز في {station.period}؟</h3>{station.tasks.length?<div className="period-task-card">{station.tasks.map(task=><div key={task.name} className={`period-task-row ${task.done?"task-done":""}`}><h4>{task.name}</h4><b>{task.meta}</b>{task.done?<span className="task-complete">تم</span>:<button onClick={()=>onStart(task.activity)}>ابدأ</button>}</div>)}</div>:<div className="empty-period"><p>لا نشاط هنا الآن.</p><span>أضفه من الخطة حين تقرر أنه يستحق مكانًا.</span></div>}</section>
 </section>
}
function Head({kicker,title,text}:{kicker:string;title:string;text:string}){return <div className="screen-head"><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{text}</p></div>}
function SheetHead({kicker,title}:{kicker:string;title:string}){return <div className="sheet-head"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div><button aria-label="إغلاق" onClick={e=>(e.currentTarget.closest("dialog") as HTMLDialogElement).close()}>×</button></div>}
function Now({slot,phase,seconds,pages,elapsed,setPhase,setPages,finish,start}:any){return <section className="now-view" aria-live="polite">{phase==="idle"&&<><div className="period-block"><p className="eyebrow">{slot.period}</p><p className="until">{slot.next}</p></div><div className="quiet-arc"><span/></div><div className="now-copy"><p className="eyebrow">الآن وقت</p><h1>{slot.activity}</h1><p className="amount">{slot.amount}</p>{slot.reading&&<p className="rate">بمعدل تقريبي <b>٣ دقائق للصفحة</b></p>}<p className="note">{slot.note}</p></div><button className="primary" onClick={start}>{slot.reading?"ابدأ القراءة":"ابدأ"}<span>←</span></button></>}{(phase==="running"||phase==="paused")&&<div className="focus-mode"><p className="eyebrow">قيد التنفيذ</p><h1>{slot.activity}</h1><div className="timer-ring"><div><strong>{fmt(seconds)}</strong><span>باقي من جلستك</span></div></div>{slot.reading&&<div className="page-progress"><strong>{arNumber(pages)} / ٥</strong><span>صفحات</span><button disabled={pages>=5} onClick={()=>setPages((p:number)=>Math.min(5,p+1))}>أنجزت صفحة</button></div>}<div className="session-actions"><button className="soft" onClick={()=>setPhase(phase==="running"?"paused":"running")}>{phase==="running"?"إيقاف مؤقت":"استئناف"}</button><button className="text-button" onClick={finish}>إنهاء النشاط</button></div></div>}{phase==="done"&&<div className="done-state"><span className="done-mark">✓</span><p className="eyebrow">تمت.</p><h1>{elapsed<60?"لحظات":`${arNumber(Math.max(1,Math.round(elapsed/60)))} دقيقة`}</h1><p>الآن وقتك لك.</p><button className="soft" onClick={()=>setPhase("idle")}>عودة بهدوء</button></div>}</section>}
function Achievements({records,plan,range}:{records:ExecutionRecord[];plan:PlannedActivity[];range:string}){
 const days=range==="week"?7:30,bucketCount=range==="week"?7:4,now=Date.now(),cutoff=now-days*86400000;
 const visible=records.filter(record=>new Date(record.completedAt).getTime()>=cutoff);
 const arabicToNumber=(value:string)=>Number(value.replace(/[٠-٩]/g,digit=>"٠١٢٣٤٥٦٧٨٩".indexOf(digit).toString()).match(/\d+/)?.[0]??1);
 const targetSessions=(activity:PlannedActivity)=>activity.schedule.mode==="daily"?days:activity.schedule.mode==="flexible"?arabicToNumber(activity.schedule.value)*(range==="week"?1:4):Math.max(1,weekDays.filter(day=>activity.schedule.value.includes(day)).length)*(range==="week"?1:4);
 const rows=plan.map(activity=>{const activityRecords=visible.filter(record=>record.activityId===activity.id||(!record.activityId&&record.activity===activity.name));const planned=targetSessions(activity),actual=activityRecords.length,minutes=activityRecords.reduce((sum,record)=>sum+record.minutes,0),average=actual?minutes/actual:0;return{activity,planned,actual,minutes,average,difference:actual-planned}});
 const plannedMinutes=rows.reduce((sum,row)=>sum+row.planned*row.activity.expectedMinutes,0),actualMinutes=visible.reduce((sum,record)=>sum+record.minutes,0);
 const buckets=Array.from({length:bucketCount},()=>0);visible.forEach(record=>{const age=Math.max(0,now-new Date(record.completedAt).getTime()),index=Math.max(0,Math.min(bucketCount-1,bucketCount-1-Math.floor(age/(days*86400000/bucketCount))));buckets[index]+=record.minutes});
 const cumulative=buckets.reduce<number[]>((values,value,index)=>[...values,value+(values[index-1]??0)],[]),plannedCumulative=Array.from({length:bucketCount},(_,index)=>plannedMinutes*((index+1)/bucketCount));
 const maxValue=Math.max(1,plannedMinutes,actualMinutes),point=(value:number,index:number)=>`${20+(index*(280/Math.max(1,bucketCount-1)))},${145-(value/maxValue)*112}`;
 const actualPoints=cumulative.map(point).join(" "),plannedPoints=plannedCumulative.map(point).join(" ");
 const labels=range==="week"?["س","ح","ن","ث","ر","خ","ج"]:["أسبوع ١","أسبوع ٢","أسبوع ٣","أسبوع ٤"];
 const plannedSessions=rows.reduce((sum,row)=>sum+row.planned,0),actualSessions=rows.reduce((sum,row)=>sum+row.actual,0),progress=plannedSessions?Math.round(actualSessions/plannedSessions*100):0;
 const maxBucket=Math.max(1,...buckets),activeBuckets=buckets.filter(Boolean).length;
 const insightRows=rows.filter(row=>row.actual>0),expectedAverage=insightRows.length?insightRows.reduce((sum,row)=>sum+row.activity.expectedMinutes,0)/insightRows.length:0,actualAverage=actualSessions?actualMinutes/actualSessions:0;
 const status=(difference:number)=>difference>0?{label:"متقدم",key:"positive"}:difference===0?{label:"على المسار",key:"track"}:difference===-1?{label:"قريب",key:"close"}:{label:"يحتاج مكانًا",key:"needs"};
 return <div className="progress-dashboard">
  <section className="progress-chart-card"><div className="chart-heading"><div><p>التقدم الزمني</p><h2>{durationLabel(actualMinutes)}</h2></div><div className="chart-legend"><span><i className="actual"/>المنجز</span><span><i className="planned"/>المخطط</span></div></div><svg viewBox="0 0 320 170" role="img" aria-label={`المنجز ${durationLabel(actualMinutes)} من ${durationLabel(plannedMinutes)} مخطط`}><line x1="20" y1="145" x2="300" y2="145" className="chart-axis"/><line x1="20" y1="89" x2="300" y2="89" className="chart-grid"/><line x1="20" y1="33" x2="300" y2="33" className="chart-grid"/><polyline points={plannedPoints} className="planned-line"/><polyline points={actualPoints} className="actual-line"/>{cumulative.map((value,index)=><circle key={index} cx={20+(index*(280/Math.max(1,bucketCount-1)))} cy={145-(value/maxValue)*112} r="3.5" className="actual-point"/>)}</svg><div className={`chart-labels labels-${bucketCount}`}>{labels.map(label=><span key={label}>{label}</span>)}</div><div className="chart-difference"><span>المخطط {durationLabel(plannedMinutes)}</span><b>{actualMinutes>=plannedMinutes?`متقدم بـ ${durationLabel(actualMinutes-plannedMinutes)}`:`متأخر بـ ${durationLabel(plannedMinutes-actualMinutes)}`}</b></div></section>
  <section className="progress-section"><div className="section-title"><h3>الخطة مقابل الفعلي</h3><span>{arNumber(progress)}٪</span></div>{rows.length?<div className="progress-table"><div className="table-head"><span>النشاط</span><span>المخطط</span><span>الفعلي</span><span>الحالة</span></div>{rows.map(row=>{const rowStatus=status(row.difference);return <div className="table-row" key={row.activity.id}><b>{row.activity.name}</b><span>{arNumber(row.planned)}</span><span>{arNumber(row.actual)}</span><em className={`status-${rowStatus.key}`}>{rowStatus.label}</em></div>})}</div>:<div className="empty-inline">أضف نشاطًا إلى خطتك لتظهر المقارنة.</div>}</section>
  <section className="progress-section"><div className="section-title"><h3>توزيع الإنجاز</h3><span>{activeBuckets} من {bucketCount}</span></div><div className={`distribution-chart distribution-${bucketCount}`}>{buckets.map((value,index)=><div key={index}><b style={{height:`${Math.max(value?8:2,(value/maxBucket)*82)}%`}} className={value?"has-value":""}/><span>{labels[index]}</span></div>)}</div></section>
  <section className="progress-section"><div className="section-title"><h3>المتوقع مقابل الوقت الحقيقي</h3><span>متوسط الجلسة</span></div>{insightRows.length?<div className="time-table">{insightRows.map(row=><div key={row.activity.id}><b>{row.activity.name}</b><span>توقعت {durationLabel(row.activity.expectedMinutes)}</span><span>فعليًا {durationLabel(Math.round(row.average))}</span><em>{row.average<=row.activity.expectedMinutes?`أقل بـ ${durationLabel(Math.round(row.activity.expectedMinutes-row.average))}`:`أكثر بـ ${durationLabel(Math.round(row.average-row.activity.expectedMinutes))}`}</em></div>)}</div>:<div className="empty-inline">ينكشف الفرق بعد أول جلسة حقيقية.</div>}</section>
  <section className="insights"><p>ما أصبح واضحًا</p>{visible.length?<><h3>{progress>=100?"أنت متقدم على خطتك.":progress>=70?"أنت قريب من خطتك.":"التأخر في عدد الجلسات، لا في حجمها."}</h3><span>{activeBuckets<=Math.ceil(bucketCount/3)?"إنجازك متجمع في أيام قليلة؛ توزيعه سيخفف ثقل الخطة.":"إنجازك موزع جيدًا عبر الفترة."}</span>{expectedAverage>0&&<span>{actualAverage<expectedAverage?`جلساتك أقصر من توقعك بنحو ${durationLabel(Math.round(expectedAverage-actualAverage))}.`:`جلساتك أطول من المتوقع بنحو ${durationLabel(Math.round(actualAverage-expectedAverage))}.`}</span>}</>:<><h3>لا قراءة بلا فعل.</h3><span>أكمل أول نشاط، وسيبدأ الرسم من بياناتك أنت.</span></>}</section>
 </div>
}
