"use client";
import {useMemo,useState} from "react";
import {templates} from "./data";
import {durationLabel} from "./time-engine";
import type {Appointment,ExecutionRecord,PlannedActivity,TaskItem,UnitProgress} from "./local-store";

const ar=(value:number)=>value.toLocaleString("ar-SA",{useGrouping:false});
const periods=["الصباح","الظهر","العصر","المغرب","الليل"];
const days=["السبت","الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة"];
const riyadhKey=(date:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
const dayName=(date:Date)=>new Intl.DateTimeFormat("ar-SA",{timeZone:"Asia/Riyadh",weekday:"long"}).format(date);
const isScheduled=(activity:PlannedActivity,date:Date)=>activity.schedule.mode==="daily"||Boolean(activity.schedule.days?.includes(dayName(date))||activity.schedule.value.includes(dayName(date)));
export type SectionKind="goals"|"commitments"|"tasks"|"appointments";
type Mode="current"|"results"|"archive";

export function SectionScreen({kind,plan,tasks,appointments,records,unitProgress,onEditActivity,onStartActivity,onEditTask,onEditAppointment,onCompleteTask,onQuickPrayer}:{kind:SectionKind;plan:PlannedActivity[];tasks:TaskItem[];appointments:Appointment[];records:ExecutionRecord[];unitProgress:UnitProgress[];onEditActivity:(item:PlannedActivity|null)=>void;onStartActivity:(item:PlannedActivity)=>void;onEditTask:(item:TaskItem|null)=>void;onEditAppointment:(item:Appointment|null)=>void;onCompleteTask:(item:TaskItem)=>void;onQuickPrayer:()=>void}){
 const [menu,setMenu]=useState(false),[mode,setMode]=useState<Mode>("current"),[range,setRange]=useState<"week"|"month"|"year">("week"),[goalDetail,setGoalDetail]=useState<PlannedActivity|null>(null);
 const title={goals:"الأهداف",commitments:"الالتزامات",tasks:"المهام",appointments:"المواعيد"}[kind];
 const addLabel={goals:"إضافة هدف",commitments:"إضافة التزام",tasks:"إضافة مهمة",appointments:"إضافة موعد"}[kind];
 const add=()=>kind==="goals"||kind==="commitments"?onEditActivity(null):kind==="tasks"?onEditTask(null):onEditAppointment(null);
 const items=kind==="goals"?plan.filter(x=>x.nature==="goal"):kind==="commitments"?plan.filter(x=>x.nature!=="goal"):[];
 const menuItems=kind==="goals"?["الأهداف الحالية","النتائج والإنجازات","الأهداف المحققة"]:kind==="commitments"?["الالتزامات الحالية","المرتبطة بأهداف","المستقلة","النتائج والإنجازات"]:kind==="tasks"?["المهام الحالية","النتائج والمنجز","المؤرشفة"]:["القادمة","اليوم","السابقة","الملغاة"];
 if(kind==="goals"&&goalDetail)return <GoalDashboard goal={goalDetail} plan={plan} records={records} onBack={()=>setGoalDetail(null)} onEdit={()=>onEditActivity(goalDetail)}/>;
 return <section className="screen section-screen">
  <header className="section-head"><h1>{title}</h1><div><button aria-label={`قائمة ${title}`} onClick={()=>setMenu(v=>!v)}>☰</button><button aria-label={addLabel} className="section-add" onClick={add}>+</button></div></header>
  {menu&&<div className="section-menu">{menuItems.map((label,index)=><button key={label} className={(index===0&&mode==="current")||(label.includes("النتائج")&&mode==="results")?"selected":""} onClick={()=>{setMode(label.includes("النتائج")?"results":label.includes("المحققة")||label.includes("السابقة")||label.includes("المؤرشفة")?"archive":"current");setMenu(false)}}>{label}</button>)}</div>}
  {kind!=="appointments"&&<div className="section-view-switch" role="group" aria-label={`عرض ${title}`}><button className={mode!=="results"?"selected":""} onClick={()=>setMode("current")}>الحالي</button><button className={mode==="results"?"selected":""} onClick={()=>setMode("results")}>النتائج</button></div>}
  {mode==="results"&&<><div className="result-range"><button className={range==="week"?"on":""} onClick={()=>setRange("week")}>أسبوعي</button><button className={range==="month"?"on":""} onClick={()=>setRange("month")}>شهري</button><button className={range==="year"?"on":""} onClick={()=>setRange("year")}>سنوي</button></div><SectionResults kind={kind} plan={plan} tasks={tasks} appointments={appointments} records={records} unitProgress={unitProgress} range={range}/></>}
  {mode!=="results"&&kind==="goals"&&<GoalList items={items} onOpen={setGoalDetail}/>}
  {mode!=="results"&&kind==="commitments"&&<CommitmentList items={items.filter(x=>mode!=="archive")} records={records} onEdit={onEditActivity} onStart={onStartActivity} onQuickPrayer={onQuickPrayer}/>}
  {mode!=="results"&&kind==="tasks"&&<TaskList items={tasks.filter(x=>mode==="archive"?x.completedAt:!x.completedAt)} onEdit={onEditTask} onComplete={onCompleteTask}/>} 
  {mode!=="results"&&kind==="appointments"&&(mode==="archive"?<AppointmentList items={appointments} past onEdit={onEditAppointment}/>:<AppointmentCalendar items={appointments} onEdit={onEditAppointment}/>)}
 </section>
}

function Empty({text}:{text:string}){return <div className="section-empty"><span>○</span><p>{text}</p></div>}
function GoalList({items,onOpen}:{items:PlannedActivity[];onOpen:(x:PlannedActivity)=>void}){return items.length?<div className="section-cards">{items.map(item=>{const d=item.goalDefinition,current=d?.currentValue??d?.currentMilestone??0,target=d?.targetValue??d?.targetMilestone??0,percent=d?.kind==="level"?(d.currentLevel===d.targetLevel?100:50):target?Math.round(current/target*100):0;return <button key={item.id} onClick={()=>onOpen(item)}><small>{item.template}</small><h2>{item.name}</h2><p>{d?.kind==="level"?`${d.currentLevel} ← ${d.targetLevel}`:`${ar(current)} / ${ar(target)} ${d?.unit??""}`}</p><i><span style={{width:`${Math.min(100,percent)}%`}}/></i><footer><span>{ar(percent)}٪ تقدم</span><span>يقوده: {item.supportingPlan?.actionName}</span></footer></button>})}</div>:<Empty text="لا هدف هنا بعد. اختر شيئًا يستحق أن تتقدم نحوه."/>}

function GoalDashboard({goal,plan,records,onBack,onEdit}:{goal:PlannedActivity;plan:PlannedActivity[];records:ExecutionRecord[];onBack:()=>void;onEdit:()=>void}){
 const [range,setRange]=useState<"week"|"month"|"year">("week");
 const definition=goal.goalDefinition;
 const linked=plan.find(item=>item.parentGoalId===goal.id||item.id===goal.linkedCommitmentId);
 const current=definition?.currentValue??definition?.currentMilestone??0;
 const target=definition?.targetValue??definition?.targetMilestone??0;
 const percent=definition?.kind==="level"?(definition.currentLevel===definition.targetLevel?100:50):target?Math.min(100,Math.round(current/target*100)):0;
 const remaining=Math.max(0,target-current);
 const daysCount=range==="week"?7:range==="month"?30:365;
 const now=new Date();
 const dates=Array.from({length:daysCount},(_,index)=>{const date=new Date(now);date.setHours(12,0,0,0);date.setDate(date.getDate()-(daysCount-1-index));return date});
 const doneOn=(date:Date)=>Boolean(linked&&records.some(record=>record.activityId===linked.id&&record.status!=="missed"&&riyadhKey(new Date(record.completedAt))===riyadhKey(date)));
 const plannedOn=(date:Date)=>Boolean(linked&&isScheduled(linked,date));
 const planned=dates.filter(plannedOn).length;
 const completed=dates.filter(date=>plannedOn(date)&&doneOn(date)).length;
 const late=Math.max(0,planned-completed);
 const completion=planned?Math.round(completed/planned*100):0;
 const minutes=records.filter(record=>record.activityId===linked?.id&&new Date(record.completedAt).getTime()>=dates[0].getTime()).reduce((sum,record)=>sum+record.minutes,0);
 const weekly=Array.from({length:4},(_,index)=>{const segment=dates.slice(Math.max(0,dates.length-(index+1)*7),dates.length-index*7);return {label:`أسبوع ${ar(4-index)}`,planned:segment.filter(plannedOn).length,completed:segment.filter(date=>plannedOn(date)&&doneOn(date)).length}}).reverse();
 const yearly=Array.from({length:12},(_,index)=>{const value=records.filter(record=>record.activityId===linked?.id&&new Date(record.completedAt).getFullYear()===now.getFullYear()&&new Date(record.completedAt).getMonth()===index).length;return {label:ar(index+1),value}});
 const chartRows=range==="month"?weekly.map(item=>({label:item.label,planned:item.planned,completed:item.completed})):yearly.map(item=>({label:item.label,planned:Math.max(1,Math.round((linked?.schedule.mode==="daily"?30:(linked?.schedule.days?.length??1)*4)/12)),completed:item.value}));
 const chartMax=Math.max(1,...chartRows.map(item=>Math.max(item.planned,item.completed)));
 const dayRows=dates.slice(-7);
 return <section className="screen goal-dashboard slide-in-left"><header className="goal-detail-head"><button onClick={onBack} aria-label="العودة إلى الأهداف">→</button><div><small>لوحة الهدف</small><h1>{goal.name}</h1></div><button onClick={onEdit} aria-label="تعديل الهدف">⌁</button></header>
  <div className="goal-kpis"><article><span>التقدم</span><b>{definition?.kind==="level"?`${definition.currentLevel} ← ${definition.targetLevel}`:`${ar(current)} / ${ar(target)}`}</b><small>{ar(percent)}٪</small></article><article><span>المتبقي</span><b>{definition?.kind==="level"?definition.targetLevel:ar(remaining)}</b><small>{definition?.unit??"حتى الهدف"}</small></article><article><span>فارق الخطة</span><b className={late?"negative":"positive"}>{late?`-${ar(late)}`:"٠"}</b><small>{late?"استحقاقات متأخرة":"على المسار"}</small></article></div>
  <div className="goal-progress-bar"><span style={{width:`${percent}%`}}/></div>
  <div className="goal-range"><button className={range==="week"?"selected":""} onClick={()=>setRange("week")}>أسبوعي</button><button className={range==="month"?"selected":""} onClick={()=>setRange("month")}>شهري</button><button className={range==="year"?"selected":""} onClick={()=>setRange("year")}>سنوي</button></div>
  <section className="goal-plan-card"><header><div><span>الالتزام الذي يقود الهدف</span><h2>{linked?.name??goal.supportingPlan?.actionName??"لم يحدد بعد"}</h2></div><b>{ar(completed)} / {ar(planned)}</b></header><div className="goal-plan-metrics"><span>التزام {ar(completion)}٪</span><span>{durationLabel(minutes)} وقت فعلي</span><span>{ar(late)} متأخر</span></div></section>
  {range==="week"?<section className="goal-week-table"><h2>هذا الأسبوع</h2><div className="goal-table-head"><span>اليوم</span><span>المخطط</span><span>المنجز</span><span>الفارق</span></div>{dayRows.map(date=>{const due=plannedOn(date),done=due&&doneOn(date);return <div key={riyadhKey(date)}><b>{["ح","ن","ث","ر","خ","ج","س"][date.getDay()]}</b><span>{due?"١":"—"}</span><span className={done?"done":""}>{done?"١":"—"}</span><span className={due&&!done?"late":""}>{due&&!done?"-١":"٠"}</span></div>})}</section>:<section className="goal-month-chart"><header><h2>{range==="month"?"المخطط مقابل المنجز":"اتجاه التنفيذ"}</h2><span>{range==="month"?"٤ أسابيع":"١٢ شهرًا"}</span></header><div className="goal-bars">{chartRows.map((item,index)=><div key={index}><i className="planned" style={{height:`${Math.max(8,item.planned/chartMax*100)}%`}}/><i className="actual" style={{height:`${Math.max(4,item.completed/chartMax*100)}%`}}/><span>{item.label}</span></div>)}</div></section>}
 </section>
}
function CommitmentList({items,records,onEdit,onStart,onQuickPrayer}:{items:PlannedActivity[];records:ExecutionRecord[];onEdit:(x:PlannedActivity)=>void;onStart:(x:PlannedActivity)=>void;onQuickPrayer:()=>void}){return items.length?<div className="section-cards">{items.map(item=>{const done=records.filter(r=>r.activityId===item.id).length,target=item.schedule.mode==="daily"?7:Math.max(1,item.schedule.days?.length??1);return <button key={item.id} onClick={()=>item.unitTracking?onStart(item):item.name.includes("الصلاة")?onQuickPrayer():onEdit(item)}><small>{item.parentGoalId?"مرتبط بهدف":"التزام مستقل"} · {item.template}</small><h2>{item.name}</h2><p>{item.unitTracking?`${ar(item.unitTracking.target)} في اليوم · ${item.unitTracking.method==="units"?"وحدات":"عداد"}`:item.schedule.value}</p><footer><span>{ar(done)} / {ar(target)} هذا الأسبوع</span><span>{item.unitTracking?"افتح الورد":item.name.includes("الصلاة")?"تسجيل سريع":`${target?ar(Math.min(100,Math.round(done/target*100))):"٠"}٪`}</span></footer></button>})}</div>:<Empty text="لا التزام هنا بعد. أضف ما تريد المحافظة عليه."/>}
function TaskList({items,onEdit,onComplete}:{items:TaskItem[];onEdit:(x:TaskItem)=>void;onComplete:(x:TaskItem)=>void}){return items.length?<div className="task-list">{items.map(item=><article key={item.id}><button className="task-check" onClick={()=>onComplete(item)}>{item.completedAt?"✓":""}</button><button onClick={()=>onEdit(item)}><h3>{item.title}</h3><p>{item.date||"دون تاريخ"}{item.time?` · ${item.time}`:""}{item.urgent?" · مستعجلة":""}</p></button></article>)}</div>:<Empty text="لا مهمة هنا. رأسك أخف قليلًا."/>}
function AppointmentList({items,past,onEdit}:{items:Appointment[];past:boolean;onEdit:(x:Appointment)=>void}){const now=new Date(),filtered=items.filter(x=>(new Date(`${x.date}T${x.time}`)<now)===past);return filtered.length?<div className="appointment-list">{filtered.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(item=><button key={item.id} onClick={()=>onEdit(item)}><span>{item.date}</span><h3>{item.title}</h3><b>{item.time}</b></button>)}</div>:<Empty text={past?"لا مواعيد سابقة.":"لا مواعيد قادمة."}/>} 

function AppointmentCalendar({items,onEdit}:{items:Appointment[];onEdit:(x:Appointment)=>void}){
 const [calendar,setCalendar]=useState<"gregory"|"islamic">("gregory"),[anchor,setAnchor]=useState(()=>new Date());
 const locale=calendar==="islamic"?"en-US-u-ca-islamic-umalqura":"en-US-u-ca-gregory";
 const parts=(date:Date)=>{const values=new Intl.DateTimeFormat(locale,{year:"numeric",month:"numeric",day:"numeric"}).formatToParts(date);const read=(type:string)=>Number(values.find(value=>value.type===type)?.value??0);return{year:read("year"),month:read("month"),day:read("day")}};
 const anchorParts=parts(anchor),monthStart=new Date(anchor);monthStart.setHours(12,0,0,0);monthStart.setDate(monthStart.getDate()-anchorParts.day+1);
 const monthDates:Array<Date>=[];for(let index=0;index<32;index++){const date=new Date(monthStart);date.setDate(monthStart.getDate()+index);const value=parts(date);if(value.month!==anchorParts.month||value.year!==anchorParts.year)break;monthDates.push(date)}
 const dateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
 const monthKeys=new Set(monthDates.map(dateKey)),monthItems=items.filter(item=>monthKeys.has(item.date)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 const title=new Intl.DateTimeFormat(calendar==="islamic"?"ar-SA-u-ca-islamic-umalqura":"ar-SA-u-ca-gregory",{month:"long",year:"numeric"}).format(anchor);
 const leading=(monthStart.getDay()+1)%7,today=dateKey(new Date());
 const moveMonth=(delta:number)=>{const date=new Date(monthStart);date.setDate(monthStart.getDate()+(delta>0?monthDates.length:-1));setAnchor(date)};
 const changeCalendar=(next:"gregory"|"islamic")=>{setCalendar(next);setAnchor(new Date())};
 return <div className="appointments-calendar-view">
  <div className="calendar-kind-switch" role="group" aria-label="نوع التقويم"><button className={calendar==="gregory"?"selected":""} onClick={()=>changeCalendar("gregory")}>ميلادي</button><button className={calendar==="islamic"?"selected":""} onClick={()=>changeCalendar("islamic")}>هجري</button></div>
  <section className="month-calendar"><header><button onClick={()=>moveMonth(-1)} aria-label="الشهر السابق">→</button><h2>{title}</h2><button onClick={()=>moveMonth(1)} aria-label="الشهر القادم">←</button></header><div className="calendar-weekdays">{["س","ح","ن","ث","ر","خ","ج"].map(day=><b key={day}>{day}</b>)}</div><div className="calendar-days">{Array.from({length:leading},(_,index)=><i key={`blank-${index}`}/>) }{monthDates.map(date=>{const key=dateKey(date),count=items.filter(item=>item.date===key).length;return <button key={key} className={`${key===today?"today":""} ${count?"has-appointment":""}`} onClick={()=>{const appointment=items.find(item=>item.date===key);if(appointment)onEdit(appointment)}} aria-label={`${new Intl.DateTimeFormat("ar-SA",{weekday:"long"}).format(date)} ${ar(parts(date).day)}${count?`، ${ar(count)} مواعيد`:""}`}><span>{ar(parts(date).day)}</span>{count>0&&<i>{ar(count)}</i>}</button>})}</div></section>
  <div className="month-appointments"><header><h2>مواعيد هذا الشهر</h2><span>{ar(monthItems.length)}</span></header>{monthItems.length?<div className="appointment-list">{monthItems.map(item=><button key={item.id} onClick={()=>onEdit(item)}><span>{new Intl.DateTimeFormat(calendar==="islamic"?"ar-SA-u-ca-islamic-umalqura":"ar-SA-u-ca-gregory",{day:"numeric",month:"short"}).format(new Date(`${item.date}T12:00:00`))}</span><h3>{item.title}</h3><b>{new Intl.DateTimeFormat("ar-SA",{hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(`${item.date}T${item.time}`))}</b></button>)}</div>:<Empty text="لا مواعيد في هذا الشهر."/>}</div>
 </div>
}

function SectionResults({kind,plan,tasks,appointments,records,unitProgress,range}:{kind:SectionKind;plan:PlannedActivity[];tasks:TaskItem[];appointments:Appointment[];records:ExecutionRecord[];unitProgress:UnitProgress[];range:"week"|"month"|"year"}){
 const daysCount=range==="week"?7:range==="month"?30:365,cutoff=Date.now()-daysCount*86400000,visible=records.filter(x=>new Date(x.completedAt).getTime()>=cutoff);
 if(kind==="goals"){const goals=plan.filter(x=>x.nature==="goal"),bucketCount=range==="year"?12:range==="month"?4:7,linkedIds=plan.filter(x=>x.parentGoalId).map(x=>x.id),goalRecords=visible.filter(x=>linkedIds.includes(x.activityId??"")),values=Array.from({length:bucketCount},(_,index)=>{const end=cutoff+((index+1)/bucketCount)*daysCount*86400000;return goalRecords.filter(x=>new Date(x.completedAt).getTime()<=end).length});return <div className="output-board"><h2>ما تحقق من أهدافك</h2>{goals.map(g=>{const d=g.goalDefinition,c=d?.currentValue??d?.currentMilestone??0,t=d?.targetValue??d?.targetMilestone??0,p=d?.kind==="level"?(d.currentLevel===d.targetLevel?100:50):t?Math.round(c/t*100):0;return <article key={g.id}><div><b>{g.name}</b><span>{d?.kind==="level"?`${d.currentLevel} ← ${d.targetLevel}`:`${ar(c)} من ${ar(t)} ${d?.unit??""}`}</span></div><strong>{ar(p)}٪</strong><i><span style={{width:`${p}%`}}/></i></article>})}{goalRecords.length?<Trend values={values}/>:<p className="output-empty">يظهر تطورك عبر الزمن بعد أول تنفيذ للالتزام المرتبط.</p>}</div>}
 if(kind==="commitments"){const commitments=plan.filter(x=>x.nature!=="goal"),rangeDates=Array.from({length:daysCount},(_,index)=>{const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-(daysCount-1-index));return date}),rangeKeys=new Set(rangeDates.map(riyadhKey)),progressInRange=unitProgress.filter(item=>rangeKeys.has(item.date)&&commitments.some(commitment=>commitment.id===item.activityId)),completedOn=(activity:PlannedActivity,date:Date)=>{const key=riyadhKey(date);return visible.some(record=>record.activityId===activity.id&&record.status!=="missed"&&(record.dueKey===key||riyadhKey(new Date(record.completedAt))===key))||progressInRange.some(progress=>progress.activityId===activity.id&&progress.date===key&&Boolean(progress.completedAt))},duePairs=commitments.flatMap(activity=>rangeDates.filter(date=>isScheduled(activity,date)).map(date=>({activity,date}))),due=duePairs.length,done=duePairs.filter(({activity,date})=>completedOn(activity,date)).length,bucketCount=range==="year"?12:range==="month"?4:7;const buckets=Array.from({length:bucketCount},(_,index)=>{const bucketDates=rangeDates.filter((_,dayIndex)=>Math.floor(dayIndex*bucketCount/daysCount)===index),pairs=commitments.flatMap(activity=>bucketDates.filter(date=>isScheduled(activity,date)).map(date=>({activity,date}))),count=pairs.filter(({activity,date})=>completedOn(activity,date)).length;return Math.min(100,Math.round(count/Math.max(1,pairs.length)*100))});const unitTotals=progressInRange.reduce((total,progress)=>{const activity=commitments.find(item=>item.id===progress.activityId);if(!activity?.unitTracking)return total;activity.unitTracking.periods.forEach(period=>{const target=progress.targetByPeriod?.[period.id]??period.target,byCounter=progress.counterByPeriod[period.id]??0,byUnits=(progress.completedUnitsByPeriod[period.id]?.length??0)*period.unitValue;total.done+=Math.min(target,Math.max(byCounter,byUnits));total.target+=target});return total},{done:0,target:0});return <div className="output-board"><div className="output-hero"><small>مدى الالتزام</small><strong>{ar(done)} / {ar(due)}</strong><b>{due?ar(Math.round(done/due*100)):"٠"}٪</b></div>{unitTotals.target>0&&<div className="unit-output-summary"><span>ما أنجزته داخل الأوراد والوحدات</span><b>{ar(unitTotals.done)} <small>من</small> {ar(unitTotals.target)}</b></div>}{range==="week"?<DueGrid commitments={commitments} records={visible} unitProgress={progressInRange}/>:<Trend values={buckets}/>}</div>}
 if(kind==="tasks"){const done=tasks.filter(x=>x.completedAt&&new Date(x.completedAt).getTime()>=cutoff);return <div className="output-board"><div className="output-hero"><small>مهام أنجزتها</small><strong>{ar(done.length)}</strong><b>{range==="week"?"هذا الأسبوع":range==="month"?"هذا الشهر":"هذه السنة"}</b></div><div className="done-task-output">{done.map(x=><p key={x.id}>✓ {x.title}</p>)}</div></div>}
 const past=appointments.filter(x=>new Date(`${x.date}T${x.time}`)<new Date());return <div className="output-board"><h2>سجل المواعيد</h2>{past.map(x=><article key={x.id}><div><b>{x.title}</b><span>{x.date} · {x.time}</span></div></article>)}</div>
}
function Trend({values}:{values:number[]}){const max=Math.max(...values,1);return <div className="trend-chart" aria-label="اتجاه النتائج">{values.map((v,i)=><i key={i} style={{height:`${Math.max(8,v/max*100)}%`}}><span>{ar(v)}٪</span></i>)}</div>}
function DueGrid({commitments,records,unitProgress}:{commitments:PlannedActivity[];records:ExecutionRecord[];unitProgress:UnitProgress[]}){const now=new Date(),week=Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()-((now.getDay()+1)%7)+i);return d});return <div className="due-grid"><span/><b>س</b><b>ح</b><b>ن</b><b>ث</b><b>ر</b><b>خ</b><b>ج</b>{commitments.map(item=><div key={item.id} className="due-row"><strong title={item.name}>{item.name.slice(0,1)}</strong>{week.map((date,i)=>{const key=riyadhKey(date),due=isScheduled(item,date),completed=records.some(r=>r.activityId===item.id&&r.status!=="missed"&&(r.dueKey===key||riyadhKey(new Date(r.completedAt))===key))||unitProgress.some(progress=>progress.activityId===item.id&&progress.date===key&&Boolean(progress.completedAt));return <i key={i} className={!due?"not-due":completed?"done":"missed"}>{!due?"":completed?"✓":"·"}</i>})}</div>)}</div>}

export function TaskDialog({editing,onSave,onDelete}:{editing:TaskItem|null;onSave:(x:TaskItem)=>void;onDelete:(id:string)=>void}){const [title,setTitle]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[urgent,setUrgent]=useState(false);useMemo(()=>{setTitle(editing?.title??"");setDate(editing?.date??"");setTime(editing?.time??"");setUrgent(editing?.urgent??false)},[editing]);return <dialog id="task-sheet" className="sheet quick-sheet"><header><div><p>مهمة</p><h2>ماذا تريد أن تنجز؟</h2></div><button onClick={e=>(e.currentTarget.closest("dialog") as HTMLDialogElement).close()}>×</button></header><label>المهمة<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="مثال: إرسال التقرير"/></label><div className="split-fields"><label>التاريخ <small>اختياري</small><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>الوقت <small>اختياري</small><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><label className="urgent-check"><input type="checkbox" checked={urgent} onChange={e=>setUrgent(e.target.checked)}/> مستعجلة</label><button className="primary" disabled={!title.trim()} onClick={()=>{onSave({id:editing?.id??`task-${Date.now()}`,title:title.trim(),date:date||undefined,time:time||undefined,urgent,completedAt:editing?.completedAt,reminder:time?{mode:"time",value:time}:{mode:"none"}});(document.getElementById("task-sheet") as HTMLDialogElement).close()}}>{editing?"حفظ":"أضف المهمة"}</button>{editing&&<button className="delete-activity" onClick={()=>onDelete(editing.id)}>حذف المهمة</button>}</dialog>}

export function ProfileDrawer({open,onClose,calendarMode,onCalendarChange,settings}:{open:boolean;onClose:()=>void;calendarMode:"islamic"|"gregory";onCalendarChange:(x:"islamic"|"gregory")=>void;settings:{title:string;note:string}[]}){return <><div className={`drawer-backdrop ${open?"open":""}`} onClick={onClose}/><aside className={`you-drawer ${open?"open":""}`}><div className="drawer-head"><div><span className="brand-mark">س</span><div><b>أنت</b><small>كما تحب أن تُعامَل</small></div></div><button onClick={onClose}>×</button></div><section className="calendar-setting"><div><h3>التاريخ</h3><p>كيف تريد أن ترى أيامك؟</p></div><div className="calendar-switch"><button className={calendarMode==="islamic"?"selected":""} onClick={()=>onCalendarChange("islamic")}>هجري</button><button className={calendarMode==="gregory"?"selected":""} onClick={()=>onCalendarChange("gregory")}>ميلادي</button></div></section><div className="settings-list">{settings.map(x=><button key={x.title}><div><h3>{x.title}</h3><p>{x.note}</p></div><span>‹</span></button>)}</div></aside></>}
